Added labels attr for Database User resource
mongodb/terraform-provider-mongodbatlas pull request #100
Opened 2020-01-06 21:08 UTC by PacoDw

- Added `labels` attribute to allow create multiple labels for each database user resource
- Added Test case using dynamic labels attribute
- Updated the documentation and vendor files

### Example Usage 
```hcl
resource "mongodbatlas_database_user" "test" {
  username      = "test-acc-username"
  password      = "test-acc-password"
  project_id    = "<PROJECT-ID>"
  database_name = "admin"

  roles {
    role_name     = "readWrite"
    database_name = "dbforApp"
  }
  roles {
    role_name     = "readAnyDatabase"
    database_name = "admin"
  }

  labels {
    key   = "key 1"
    value = "value 1"
  }
  labels {
    key   = "key 2"
    value = "value 2"
  }
}
```

2020-01-08 04:15 UTC, themantissa requested changes
Looks good but missing the documentation updates for the data source.   That's all I think we need.

2020-01-17 20:11 UTC, marinsalinas requested changes
Could you please update from master and get the latest version of the client code?

2020-01-17 20:12 UTC, PacoDw commented
yes, thank you! 👍

2020-01-17 21:58 UTC, themantissa approved these changes
LGTM

2020-01-18 18:00 UTC, merged