INTMDB-472: Update_snapshots doesn't save at TF state with mongodbatlas_cloud_backup_schedule resource
mongodb/terraform-provider-mongodbatlas pull request #1014
Opened 2023-01-18 01:01 UTC by martinstibbe

## Description

Update_snapshots doesn't save at TF state with mongodbatlas_cloud_backup_schedule resource workaround skip update_snapshots on read as API does not return current value

Link to any related issue(s):
https://github.com/mongodb/terraform-provider-mongodbatlas/issues/904

## Type of change:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Documentation fix/enhancement

## Required Checklist:

- [ ] I have signed the [MongoDB CLA](https://www.mongodb.com/legal/contributor-agreement)
- [ ] I have read the [contribution guidelines](https://github.com/mongodb/terraform-provider-mongodbatlas/blob/master/CONTRIBUTING.md)
- [ ] I have added tests that prove my fix is effective or that my feature works per HashiCorp requirements
- [ ] I have added any necessary documentation (if appropriate)
- [ ] I have run make fmt and formatted my code

## Further comments

2023-01-18 04:46 UTC, Zuhairahmed requested changes
Minor comment, ping me in case you need to chat on this one

2023-01-18 04:46 UTC, Zuhairahmed commented on website/docs/r/cloud_backup_schedule.html.markdown
> +  **Note** This parameter is not updated on return from API
@martinstibbe this Note is not clear (at least to me). do you mind making more descriptive to help future users?

2023-01-18 09:14 UTC, andreaangiolillo approved these changes
LGTM

2023-01-19 03:30 UTC, Zuhairahmed commented on website/docs/r/cloud_backup_schedule.html.markdown
> +  **Note** This parameter is not updated on return from API
```suggestion
  **Note** This parameter does not return updates on return from API, this is a feature of the Atlas Admin API itself and not Terraform.  For more details about this resource see: https://www.mongodb.com/docs/atlas/reference/api-resources-spec/#tag/Cloud-Backup-Schedule
```

2023-01-19 03:31 UTC, Zuhairahmed approved these changes
LGTM, added additional commit cleaning up language a bit and linking to new docs

2023-01-19 03:42 UTC, merged