Fix diskIOPS attribute for GCP and Azure
mongodb/terraform-provider-mongodbatlas pull request #11
Opened 2019-08-28 17:30 UTC by PacoDw

- Documentation was improved adding GCP and Azure examples.
- Tests were added for GCP and Azure.

## Example Usage

### Example AWS cluster.

```hcl
resource "mongodbatlas_cluster" "cluster-test" {
  project_id   = "<YOUR-PROJECT-ID>"
  name         = "cluster-test"
  num_shards   = 1

  replication_factor           = 3
  backup_enabled               = true
  auto_scaling_disk_gb_enabled = true
  mongo_db_major_version       = "4.0"

  //Provider Settings "block"
  provider_name               = "AWS"
  disk_size_gb                = 100
  provider_disk_iops          = 300
  provider_encrypt_ebs_volume = false
  provider_instance_size_name = "M40"
  provider_region_name        = "US_EAST_1"
}
```

### Example Azure cluster.

```hcl
resource "mongodbatlas_cluster" "test" {
  project_id   = "<YOUR-PROJECT-ID>"
  name         = "test"
  num_shards   = 1
  
  replication_factor           = 3
  backup_enabled               = true
  auto_scaling_disk_gb_enabled = true
  mongo_db_major_version       = "4.0"
  
  //Provider Settings "block"
  provider_name               = "AZURE"  
  provider_disk_type_name     = "P6"
  provider_instance_size_name = "M30"
  provider_region_name        = "US_EAST_2"
}
```

### Example GCP cluster.

```hcl
resource "mongodbatlas_cluster" "test" {
  project_id   = "<YOUR-PROJECT-ID>"
  name         = "test"
  num_shards   = 1
  
  replication_factor           = 3
  backup_enabled               = true
  auto_scaling_disk_gb_enabled = true
  mongo_db_major_version       = "4.0"
  
  //Provider Settings "block"
  provider_name               = "GCP"
  disk_size_gb                = 40
  provider_instance_size_name = "M30"
  provider_region_name        = "US_EAST_4"
}
```
closes #2 and #9

2019-08-28 20:35 UTC, marinsalinas commented on mongodbatlas/resource_mongodbatlas_cluster.go
> +	if d.Get("provider_name") != "AWS" {
It's good to have these validations to avoid errors from the API, but I think creating a function that passes the provider name and a slice of attribute names like this would be more appropriate:

```go
func validateAttrsForAWS(providerName string, attrNames []string) error
func validateAttrsForGCP(providerName string, attrNames []string) error
func validateAttrsForAzure(providerName string, attrNames []string) error
```

We can introduce this in a future enhancement.

2019-08-28 20:35 UTC, marinsalinas approved these changes

2019-08-28 20:37 UTC, PacoDw commented on mongodbatlas/resource_mongodbatlas_cluster.go
> +	if d.Get("provider_name") != "AWS" {
okay, I like it! it's very nice! 👍

2019-08-28 21:50 UTC, themantissa approved these changes
Nice work!

2019-08-28 21:50 UTC, themantissa commented on website/docs/r/cluster.html.markdown
> +  mongo_db_major_version       = "4.0"
mongo_db_major_version can be used for all 3 cloud providers so to reduce confusion I'd add to all 3 - so just add to AWS.

2019-08-28 21:50 UTC, themantissa commented on website/docs/r/cluster.html.markdown
> +  disk_size_gb = 40
For GCP and AWS I would move disk_size_gb into the Provider Settings block.

2019-08-28 21:50 UTC, themantissa requested changes
Just a few changes doc changes needed and all good.

2019-08-28 22:33 UTC, PacoDw commented on website/docs/r/cluster.html.markdown
> +  mongo_db_major_version       = "4.0"
Thanks, @themantissa! 👍

2019-08-28 22:33 UTC, PacoDw commented on website/docs/r/cluster.html.markdown
> +  disk_size_gb = 40
It's a great idea, thank you!

2019-08-29 14:59 UTC, themantissa approved these changes

2019-09-03 08:36 UTC, teroxik commented
Tested this on azure, and seems to be working ok. Can we get it in please?

2019-09-03 16:07 UTC, merged

2019-09-03 16:38 UTC, aliciaalcalde commented
It's works.
Thank you so much!!!