INTMDB-658: [Terraform] Upgrade to go1.20
mongodb/terraform-provider-mongodbatlas pull request #1153
Opened 2023-05-02 16:12 UTC by andreaangiolillo

## Description

Please include a summary of the fix/feature/change, including any relevant motivation and context.

Link to any related issue(s):

## Type of change:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Documentation fix/enhancement

## Required Checklist:

- [x] I have signed the [MongoDB CLA](https://www.mongodb.com/legal/contributor-agreement)
- [x] I have read the [contribution guidelines](https://github.com/mongodb/terraform-provider-mongodbatlas/blob/master/CONTRIBUTING.md)
- [x] I have added tests that prove my fix is effective or that my feature works per HashiCorp requirements
- [x] I have added any necessary documentation (if appropriate)
- [x] I have run make fmt and formatted my code

## Further comments

2023-05-03 08:43 UTC, gssbzn commented on mongodbatlas/provider_test.go
> +func testCheckPeeringEnvAWS(tb testing.TB) {
were these because of a linter change?

2023-05-03 08:43 UTC, gssbzn approved these changes
LGTM

2023-05-03 08:57 UTC, andreaangiolillo commented on mongodbatlas/provider_test.go
> +func testCheckPeeringEnvAWS(tb testing.TB) {
yes

2023-05-03 09:00 UTC, andreaangiolillo commented on mongodbatlas/provider_test.go
> +func testCheckPeeringEnvAWS(tb testing.TB) {
Here is the lint action that was failing https://github.com/mongodb/terraform-provider-mongodbatlas/actions/runs/4863632956/jobs/8671593065

```bash
2023-05-02T16:41:45.6158922Z Running [/home/runner/golangci-lint-1.52.2-linux-amd64/golangci-lint run --out-format=github-actions --timeout 9m0s] in [] ...
2023-05-02T16:44:05.9298193Z ##[error]sloppyTestFuncName: function checkFederatedSettings should be of form TestXXX(t *testing.T) (gocritic)
2023-05-02T16:44:05.9302416Z ##[error]sloppyTestFuncName: function checkLDAP should be of form TestXXX(t *testing.T) (gocritic)
2023-05-02T16:44:05.9304193Z ##[error]sloppyTestFuncName: function checkTeamsIds should be of form TestXXX(t *testing.T) (gocritic)
2023-05-02T16:44:05.9306001Z ##[error]sloppyTestFuncName: function testAccPreCheck looks like a test helper, consider to change 1st param to 'tb testing.TB' (gocritic)
2023-05-02T16:44:05.9307626Z ##[error]sloppyTestFuncName: function testAccPreCheckBetaFeatures looks like a test helper, consider to change 1st param to 'tb testing.TB' (gocritic)
2023-05-02T16:44:05.9309681Z ##[error]sloppyTestFuncName: function testAccPreCheckGPCEnv looks like a test helper, consider to change 1st param to 'tb testing.TB' (gocritic)
2023-05-02T16:44:05.9311304Z ##[error]sloppyTestFuncName: function testAccPreCheckGov looks like a test helper, consider to change 1st param to 'tb testing.TB' (gocritic)
2023-05-02T16:44:05.9312893Z ##[error]sloppyTestFuncName: function testCheckAwsEnv looks like a test helper, consider to change 1st param to 'tb testing.TB' (gocritic)
2023-05-02T16:44:05.9314850Z ##[error]sloppyTestFuncName: function testCheckEncryptionAtRestEnvAzure looks like a test helper, consider to change 1st param to 'tb testing.TB' (gocritic)
2023-05-02T16:44:05.9316305Z ##[error]sloppyTestFuncName: function testCheckPeeringEnvAWS looks like a test helper, consider to change 1st param to 'tb testing.TB' (gocritic)
2023-05-02T16:44:05.9317730Z ##[error]sloppyTestFuncName: function testCheckPeeringEnvAzure looks like a test helper, consider to change 1st param to 'tb testing.TB' (gocritic)
2023-05-02T16:44:05.9319210Z ##[error]sloppyTestFuncName: function testCheckPeeringEnvGCP looks like a test helper, consider to change 1st param to 'tb testing.TB' (gocritic)
```

2023-05-03 09:09 UTC, gssbzn commented on mongodbatlas/provider_test.go
> +func testCheckPeeringEnvAWS(tb testing.TB) {
interesting, thanks for sharing

2023-05-04 15:07 UTC, andreaangiolillo commented
Hi @martinstibbe 👋 Could you review this PR when you have time, please?

2023-05-10 16:24 UTC, Zuhairahmed requested changes
Synced with @martinstibbe, pushing this back to to v1.10.1 release to prevent any conflicts with on-going feature updates as part of v1.10.0 release.

2023-05-10 16:32 UTC, andreaangiolillo commented
@Zuhairahmed Should I merge the PR into master instead? Thanks!

2023-05-10 16:55 UTC, Zuhairahmed commented
> @Zuhairahmed Should I merge the PR into master instead? Thanks!

Yes please merge into master per https://mongodb.slack.com/archives/C032Q3G3Z28/p1683737491456979

2023-05-10 16:55 UTC, Zuhairahmed approved these changes

2023-05-10 18:04 UTC, merged