INTMDB-408: Remove Deprecated Resources - cloud_provider resources, private_ip_mode, NEW_RELIC and FLOWDOCK in third_party_integration resource
mongodb/terraform-provider-mongodbatlas pull request #1159
Opened 2023-05-09 12:50 UTC by martinstibbe

## Description

Please include a summary of the fix/feature/change, including any relevant motivation and context.
Remove Deprecated Resources - cloud_provider resources, private_ip_mode, NEW_RELIC and FLOWDOCK in third_party_integration resource

Link to any related issue(s):

## Type of change:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Documentation fix/enhancement

## Required Checklist:

- [x] I have signed the [MongoDB CLA](https://www.mongodb.com/legal/contributor-agreement)
- [x] I have read the [contribution guidelines](https://github.com/mongodb/terraform-provider-mongodbatlas/blob/master/CONTRIBUTING.md)
- [ ] I have added tests that prove my fix is effective or that my feature works per HashiCorp requirements
- [ ] I have added any necessary documentation (if appropriate)
- [x] I have run make fmt and formatted my code

## Further comments

2023-05-09 14:25 UTC, andreaangiolillo reviewed
reviewing the PR once the tests are fixed

2023-05-16 11:10 UTC, andreaangiolillo approved these changes
LGTM

2023-05-17 03:49 UTC, Zuhairahmed commented on mongodbatlas/resource_mongodbatlas_project_ip_access_list_test.go
> +	const ipWhiteListCount = 20
@martinstibbe just curious why this change?

2023-05-17 03:57 UTC, Zuhairahmed requested changes
@martinstibbe believe we also need to delete mongodbatlas_private_ip_mode per https://github.com/mongodb/terraform-provider-mongodbatlas/pull/988 

also can you update all docs pages to mention that each of these resources have now been fully deprecated as part of v1.10.0 release

2023-05-17 17:26 UTC, martinstibbe commented on mongodbatlas/resource_mongodbatlas_project_ip_access_list_test.go
> +	const ipWhiteListCount = 20
Runtime of Config test structure hours vs 4 minutes to verify basic IP list working

2023-05-19 03:13 UTC, Zuhairahmed approved these changes
LGTM. Thanks @martinstibbe, added another commit with a few more doc updates with fully deprecated updates. Feel free to merge after you ack.

2023-05-19 17:08 UTC, merged