Add PIT enabled argumento to Cluster Resource and Data Source
mongodb/terraform-provider-mongodbatlas pull request #126
Opened 2020-02-05 21:58 UTC by marinsalinas

Closes #104 

This branch is based on the dbusers branch, once that branch is merged I'll rebase from master and then merge it.

2020-02-05 22:03 UTC, PacoDw approved these changes
LGTM! Thank you so much :)

2020-02-06 05:00 UTC, themantissa requested changes
Nice work, just one minor doc change and we are good.

2020-02-06 05:00 UTC, themantissa commented on website/docs/r/cluster.html.markdown
> +* `pit_enabled` - (Optional) - Flag that indicates if the cluster uses Point-in-Time backups. If set to true, providerBackupEnabled must also be set to true.
One minor change, we should use the Terraform variable so change to:
* `pit_enabled` - (Optional) - Flag that indicates if the cluster uses Point-in-Time backups. If set to true, provider_backup_enabled must also be set to true.

2020-02-06 17:29 UTC, themantissa approved these changes
Nicely done, LGTM

2020-02-06 21:38 UTC, merged