Encryption At Rest: fixed issues and added an enhancement
mongodb/terraform-provider-mongodbatlas pull request #128
Opened 2020-02-10 21:19 UTC by PacoDw

closes:  #74 , #80 , #93

2020-02-10 23:45 UTC, marinsalinas approved these changes
Nice catch! LGTM!

2020-02-11 20:20 UTC, themantissa requested changes
Minor spelling/grammar and a comment.  Otherwise LGTM.

2020-02-11 20:20 UTC, themantissa commented on mongodbatlas/provider_test.go
> +func checkEncriptionAtRestEnvAzure(t *testing.T) {
Encryption is spelled wrong in the function name.

2020-02-11 20:20 UTC, themantissa commented on mongodbatlas/resource_mongodbatlas_encryption_at_rest.go
> +		return fmt.Errorf("error deleting a encryptionAtRest (%s): %s", d.Id(), err)
Better error might be "error removing encryption at rest"

2020-02-11 20:20 UTC, themantissa commented on mongodbatlas/resource_mongodbatlas_encryption_at_rest_test.go
> +	projectID := os.Getenv("MONGODB_ATLAS_PROJECT_ID")
Env var - That is much better I think than hard coded but from here forward we should be consistent (do one or the other as the standard- I think env var should be the preferred.)

2020-02-11 20:44 UTC, PacoDw commented on mongodbatlas/provider_test.go
> +func checkEncriptionAtRestEnvAzure(t *testing.T) {
Good catch!!! thanks @themantissa 👍

2020-02-13 23:09 UTC, themantissa commented
LGTM, thanks!

2020-02-13 23:56 UTC, themantissa approved these changes
Ugh, sorry forgot to change to Approve, not just comment - now approved :) thanks!

2020-02-18 10:40 UTC, rvdh commented
When can we expect this to be merged into a release? We're running into this issue and now it's not possible to update the encryption at rest key without recreating the whole cluster.

2020-02-18 15:01 UTC, merged

2020-02-18 15:44 UTC, themantissa commented
@rvdh  barring any last minute issues we plan to release 0.4.0 today.   We'll be posting two blogs and I'll link them in the issues section once live as one is an upgrade guide regarding the Project IP Whitelist changes.

In between releases please feel free to beta coming changes by building from the master branch.  Instructions are in the README file.

2020-02-18 15:49 UTC, rvdh commented
@themantissa Thats great news! :) Thanks.