deprecate: Deprecates `mongodbatlas_teams` resource and data source in favour of `mongodbatlas_team`
mongodb/terraform-provider-mongodbatlas pull request #2208
Opened 2024-04-24 13:23 UTC by AgustinBettati

## Description

Link to any related issue(s): CLOUDP-215069

### Before

- resource and data source `mongodbatlas_teams`:  Configured in the provider, defined in our docs.
- resource and data source `mongodbatlas_team`: Configured in the provider, not defined in docs.
- both `mongodbatlas_team` and `mongodbatlas_teams` map to the [same implementation](https://github.com/mongodb/terraform-provider-mongodbatlas/blob/master/internal/provider/provider_sdk2.go#L167) which is a singular implementation.

### After

- resource and data source `mongodbatlas_team`: Configured in the provider, defined in docs.
- resource and data source `mongodbatlas_teams`: Configured in the provider but marked as deprecated with a target removal of 6 months from now, defined in docs mentioning deprecation and redirecting to `mongodbatlas_team`.

This ensures no breaking changes while giving a transition period for users to move from `mongodbatlas_teams` to `mongodbatlas_team`.

## Type of change:

- [ ] Bug fix (non-breaking change which fixes an issue). Please, add the "bug" label to the PR.
- [ ] New feature (non-breaking change which adds functionality). Please, add the "enhancement" label to the PR. A migration guide must be created or updated if the new feature will go in a major version.
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected). Please, add the "breaking change" label to the PR. A migration guide must be created or updated.
- [ ] This change requires a documentation update
- [ ] Documentation fix/enhancement

## Required Checklist:

- [x] I have signed the [MongoDB CLA](https://www.mongodb.com/legal/contributor-agreement)
- [x] I have read the [contributing guides](https://github.com/mongodb/terraform-provider-mongodbatlas/blob/master/contributing/README.md)
- [x] I have checked that this change does not generate any credentials and that **they are NOT accidentally logged anywhere**.
- [x] I have added tests that prove my fix is effective or that my feature works per HashiCorp requirements
- [x] I have added any necessary documentation (if appropriate)
- [x] I have run make fmt and formatted my code
- [x] If changes include deprecations or removals, I defined an isolated PR with a relevant title as it will be used in the auto-generated changelog.
- [x] If changes include removal or addition of 3rd party GitHub actions, I updated our internal document. Reach out to the APIx Integration slack channel to get access to the internal document.

## Further comments

2024-04-24 15:16 UTC, lantoli commented on internal/service/team/data_source_team.go
> +	res.DeprecationMessage = fmt.Sprintf(constant.DeprecationDataSourceByDateWithReplacement, "April 2025", "mongodbatlas_team")
curious why so far instead of a couple of major versions from now

2024-04-24 15:17 UTC, lantoli commented on internal/service/team/resource_team.go
> +func LegacyTeamsResource() *schema.Resource {
nice idea about having this legacy functions

2024-04-24 15:18 UTC, lantoli approved these changes

2024-04-24 15:19 UTC, oarbusi approved these changes

2024-04-24 15:30 UTC, EspenAlbert approved these changes
Nice 👍 
Does the template files also need to be updated?
- https://github.com/mongodb/terraform-provider-mongodbatlas/blob/e3bdf33967f5b16db50ac639e3fe8cc06f1aef2a/templates/resources.md.tmpl#L60-L61

2024-04-24 15:31 UTC, pierwill requested changes

2024-04-24 15:31 UTC, pierwill commented on internal/common/constant/deprecation.go
> +	DeprecationDataSourceByDateWithReplacement = "this data source is deprecated and will be removed in %s, please transition to %s"
```suggestion
	DeprecationParamByDate                     = "This parameter is deprecated and will be removed by %s."
	DeprecationParamByDateWithReplacement      = "This parameter is deprecated and will be removed by %s. Please transition to %s.
	DeprecationParamByVersion                  = "This parameter is deprecated and will be removed in version %s."
	DeprecationResourceByDateWithReplacement   = "This resource is deprecated and will be removed in %s. Please transition to %s."
	DeprecationDataSourceByDateWithReplacement = "This data source is deprecated and will be removed in %s. Please transition to %s."
```

2024-04-24 15:31 UTC, pierwill commented on website/docs/d/team.html.markdown
> +-> **NOTE:** Groups and projects are synonymous terms. You may find group_id in the official documentation.
```suggestion
-> **NOTE:** Groups and projects are synonymous terms. You may find `group_id` in the official documentation.
```

2024-04-24 15:31 UTC, pierwill commented on website/docs/d/team.html.markdown
> +* `id` -	The Terraform's unique identifier used internally for state management.
```suggestion
* `id` - Terraform's unique identifier used internally for state management.
```

2024-04-24 15:31 UTC, pierwill commented on website/docs/r/team.html.markdown
> +> **IMPORTANT:** MongoDB Atlas Team limits: max 250 teams in an organization and max 100 teams per project.
```suggestion
> **IMPORTANT:** MongoDB Atlas Team are limited to a maximum of 250 teams in an organization and 100 teams per project.
```

2024-04-24 15:31 UTC, pierwill commented on website/docs/r/team.html.markdown
> +MongoDB Atlas Team limits: max 250 teams in an organization and max 100 teams per project.
ditto

2024-04-24 15:37 UTC, AgustinBettati commented on internal/service/team/data_source_team.go
> +	res.DeprecationMessage = fmt.Sprintf(constant.DeprecationDataSourceByDateWithReplacement, "April 2025", "mongodbatlas_team")
Leave reference of @Zuhairahmed input from the jira ticket:

> given this is one of our most heavily used resources would limit this clean up to only items below with no breaking changes. if there is future customer demand for breaking changes we can tackle at that time

With this in mind, and the fact that we have no rush in removing the teams resource/data source (no additional maintenance from our side) felt it would be better to give significant time before we consider the removal. Happy to adjust if there any additional considerations.

2024-04-25 14:30 UTC, AgustinBettati commented on internal/service/team/data_source_team.go
> +	res.DeprecationMessage = fmt.Sprintf(constant.DeprecationDataSourceByDateWithReplacement, "April 2025", "mongodbatlas_team")
Adjusted target removal to 6 months from now as discussed offline. cc: @lantoli @Zuhairahmed

2024-04-25 15:12 UTC, pierwill approved these changes

2024-04-25 16:13 UTC, merged