imp: team datasource add team name option
mongodb/terraform-provider-mongodbatlas pull request #253
Opened 2020-06-24 05:22 UTC by gmlp

## Description

## Type of change:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update
- [ ] Documentation fix/enhancement

## Required Checklist:

- [x] I have signed the MongoDB CLA
- [x] I have read the Terraform contribution guidelines 
- [x] I have added tests that prove my fix is effective or that my feature works per HashiCorp requirments
- [ ] I have added any necessary documentation (if appropriate)
- [x] I have run make fmt and formatted my code

## Further comments

2020-06-25 02:11 UTC, themantissa requested changes
One typo noted in comment (and tests failing), otherwise LGTM so can approved once fixed!

2020-06-25 02:11 UTC, themantissa commented on website/docs/d/team.html.markdown
> +~> **IMPORTANT:** Either `team_id` or `name` must be configurated.
just spelling typo - "must be configured"

2020-06-25 14:33 UTC, PacoDw requested changes

2020-06-25 14:33 UTC, PacoDw commented on mongodbatlas/data_source_mongodbatlas_team.go
> +				ConflictsWith: []string{"team_id"},
Maybe we can put them as a computed as well to set them and have/keep both in the TF state when one is chosen.

2020-06-25 14:33 UTC, PacoDw commented on mongodbatlas/data_source_mongodbatlas_team_test.go
> +		}
I think is better to have another test case with this specific TF configuration to test separately

2020-06-25 14:33 UTC, PacoDw commented on website/docs/d/team.html.markdown
> +}
The same that above comment, create a separate example using this case

2020-06-25 14:33 UTC, PacoDw commented on website/docs/d/team.html.markdown
>  * `name` -  The name of the team you want to create.
Note that name is put here has a computed but your schema says that it's not, as we will change the `name` and `team_id` as computed, we need to put `team_id` here

2020-06-26 18:12 UTC, PacoDw approved these changes

2020-06-26 21:14 UTC, themantissa approved these changes
LGTM!

2020-06-29 18:20 UTC, merged