add: project_ip_whitelist datasource
mongodb/terraform-provider-mongodbatlas pull request #254
Opened 2020-06-29 15:35 UTC by gmlp

## Description

Please include a summary of the fix/feature/change, including any relevant motivation and context.

## Type of change:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Documentation fix/enhancement

## Required Checklist:

- [x] I have signed the MongoDB CLA
- [x] I have read the Terraform contribution guidelines 
- [x] I have added tests that prove my fix is effective or that my feature works per HashiCorp requirments
- [] I have added any necessary documentation (if appropriate)
- [x] I have run make fmt and formatted my code

## Further comments

2020-06-29 16:12 UTC, PacoDw requested changes

2020-06-29 16:12 UTC, PacoDw commented on mongodbatlas/data_source_mongodbatlas_project_ip_whitelist_test.go
> +			accepter_region_name	  = "us-east-1"
plz change this with `lower(replace("%[6]s", "_", "-"))`

2020-06-29 21:02 UTC, PacoDw requested changes

2020-06-29 21:02 UTC, PacoDw commented on mongodbatlas/data_source_mongodbatlas_project_ip_whitelist_test.go
> +	awsSGroup := "sg-0026348ec11780bd1"
plz change this `awsSGroup` value to `AWS_SECURITY_GROUP_ID` env variable

2020-06-29 21:12 UTC, PacoDw requested changes

2020-06-29 21:12 UTC, PacoDw commented on mongodbatlas/data_source_mongodbatlas_project_ip_whitelist_test.go
> +
plz remove the whitespace in each function

2020-06-29 21:12 UTC, PacoDw commented on mongodbatlas/data_source_mongodbatlas_project_ip_whitelist_test.go
> +
remove it as well

2020-06-29 21:12 UTC, PacoDw commented on mongodbatlas/data_source_mongodbatlas_project_ip_whitelist_test.go
> +func testAccDataMongoDBAtlasProjectIPWhitelistConfigSettingIPAddress(projectID, ipAddress, comment string) string {
Add a new line among functions plz

2020-06-29 21:42 UTC, PacoDw approved these changes
LGTM! thank you so much

2020-07-01 00:40 UTC, themantissa requested changes
A few small edits but otherwise LGTM!

2020-07-01 00:40 UTC, themantissa commented on mongodbatlas/data_source_mongodbatlas_project_ip_whitelist.go
> +		return fmt.Errorf("error getting white List IP information: %s", err)
"white List IP" is a bit confusing, should be something more like "error getting whitelist information"

2020-07-01 00:40 UTC, themantissa commented on mongodbatlas/data_source_mongodbatlas_project_ip_whitelist.go
> +		return fmt.Errorf("error setting `comment` for Project IP white list: %s", err)
Same, in this context whitelist is a single word.

2020-07-01 00:40 UTC, themantissa commented on website/docs/d/project_ip_whitelist.html.markdown
> +sidebar_current: "docs-mongodbatlas-resource-project-ip-whitelist"
Since it's a data source shouldn't this be sidebar_current: "docs-mongodbatlas-datasource-project-ip-whitelist"?

2020-07-01 00:40 UTC, themantissa commented on website/docs/d/project_ip_whitelist.html.markdown
> +~> **IMPORTANT:** In order to use AWS Security Group(s) VPC Peering must be enabled like above example.
Small grammar edit: 
 ~> **IMPORTANT:** In order to use AWS Security Group(s) VPC Peering must be enabled like in the above example.

2020-07-01 00:40 UTC, themantissa commented on website/docs/d/project_ip_whitelist.html.markdown
> +* `id` - Unique identifier used for terraform for internal manages and can be used to import.
Small  edit: 
* `id` - Unique identifier used by Terraform for internal management and can be used to import.

2020-07-01 18:54 UTC, gmlp commented
@themantissa, done, thanks.

2020-07-01 21:09 UTC, themantissa approved these changes
LGTM!

2020-07-02 16:24 UTC, merged