New resource and datasource for Project IP Access list
mongodb/terraform-provider-mongodbatlas pull request #332
Opened 2020-10-15 23:38 UTC by coderGo93

## Description
- Added new resources, data sources and its tests for Project IP Access List 
- Updated vendor
- Changed behavior in github actions when you can run if the branch is master too instead of only with label.

Link to any related issue(s):

## Type of change:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Documentation fix/enhancement

## Required Checklist:

- [ ] I have signed the [MongoDB CLA](https://www.mongodb.com/legal/contributor-agreement)
- [ ] I have read the Terraform contribution guidelines
- [ ] I have added tests that prove my fix is effective or that my feature works per HashiCorp requirments
- [ ] I have added any necessary documentation (if appropriate)
- [ ] I have run make fmt and formatted my code

## Further comments

2020-10-16 23:06 UTC, themantissa requested changes
Just a few tiny edits to errors/docs then ready to go.  Nice job!

2020-10-16 23:06 UTC, themantissa commented on mongodbatlas/resource_mongodbatlas_project_ip_access_list.go
> +			// You must configure VPC peering for your project before you can access list an AWS security group.
The wording for this is a little different:
 			// You must configure VPC peering for your project before you can add an AWS security group to the access list.

2020-10-16 23:06 UTC, themantissa commented on mongodbatlas/resource_mongodbatlas_project_ip_access_list.go
> +			return resource.RetryableError(fmt.Errorf(errorAccessListDelete, "access list still exists"))
Access should be capitalize:
 			return resource.RetryableError(fmt.Errorf(errorAccessListDelete, "Access list still exists"))

2020-10-16 23:06 UTC, themantissa commented on mongodbatlas/data_source_mongodbatlas_project_ip_access_list.go
> +		return fmt.Errorf("error getting accessList information: %s", err)
slight edit:
 		return fmt.Errorf("Error getting access list information: %s", err)

2020-10-16 23:06 UTC, themantissa commented on mongodbatlas/data_source_mongodbatlas_project_ip_access_list.go
> +		return fmt.Errorf("error setting `cidr_block` for Project accessList: %s", err)
Small edit:
 		return fmt.Errorf("Error setting `cidr_block` for the project access list: %s", err)

2020-10-16 23:06 UTC, themantissa commented on mongodbatlas/data_source_mongodbatlas_project_ip_access_list.go
> +		return fmt.Errorf("error setting `ip_address` for Project accessList: %s", err)
return fmt.Errorf("Error setting `ip_address` for the project access list: %s", err)

2020-10-16 23:06 UTC, themantissa commented on mongodbatlas/data_source_mongodbatlas_project_ip_access_list.go
> +		return fmt.Errorf("error setting `aws_security_group` for Project accessList: %s", err)
return fmt.Errorf("Error setting `aws_security_group` for the project access list: %s", err)

2020-10-16 23:06 UTC, themantissa commented on mongodbatlas/data_source_mongodbatlas_project_ip_access_list.go
> +		return fmt.Errorf("error setting `comment` for Project accessList: %s", err)
return fmt.Errorf("Error setting `comment` for the project access list: %s", err)

2020-10-16 23:06 UTC, themantissa commented on website/docs/d/project_ip_access_list.html.markdown
> +* `project_id` - (Required) Unique identifier for the project to which you want to add one or more Access List entries.
tiny edit but we should be consistent with capitalization (this is likely from the original docs copy but just explaining why the edit):
 * `project_id` - (Required) Unique identifier for the project to which you want to add one or more access list entries.

2020-10-16 23:06 UTC, themantissa commented on website/docs/r/project_ip_access_list.html.markdown
> +* `project_id` - (Required) Unique identifier for the project to which you want to add one or more Access List entries.
same as above:
 * `project_id` - (Required) Unique identifier for the project to which you want to add one or more access list entries.

2020-10-19 22:57 UTC, leofigy commented on .github/workflows/automated-test-acceptances.yml
> +    if: ${{ github.event.label.name == 'run-testacc' || github.ref == 'refs/heads/master' }}
nice

2020-10-19 23:09 UTC, themantissa approved these changes
All I requested is here, thank you!   LGTM, if tests past and another DoU dev approves please merge. Thanks!

2020-10-19 23:32 UTC, leofigy approved these changes
LGTM

2020-10-20 03:53 UTC, merged