INTMDB-133: Added terratest for encryption at rest using iam roles
mongodb/terraform-provider-mongodbatlas pull request #369
Opened 2020-12-21 21:56 UTC by coderGo93

## Description
To use terratest locally, it will the plugin locally following this information [Plugin locations](https://www.terraform.io/docs/extend/how-terraform-works.html#plugin-locations) otherwise it will get the plugin from terraform registry website.

Link to any related issue(s):

## Type of change:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Documentation fix/enhancement

## Required Checklist:

- [ ] I have signed the [MongoDB CLA](https://www.mongodb.com/legal/contributor-agreement)
- [ ] I have read the Terraform contribution guidelines
- [ ] I have added tests that prove my fix is effective or that my feature works per HashiCorp requirments
- [ ] I have added any necessary documentation (if appropriate)
- [ ] I have run make fmt and formatted my code

## Further comments

2020-12-21 22:25 UTC, themantissa commented
@nikhil-mongo  would you be able to take a look at this example and review it?   It's for the recent add of IAM roles and the upcoming change for new use to go from IAM user to IAM roles.

2020-12-23 07:25 UTC, nikhil-mongo commented
Please add the attributes for accesskey and secret key
```
Error: error creating Encryption at Rest: PATCH https://cloud.mongodb.com/api/atlas/v1.0/groups/5dd0f66379358e17e49d6c40/encryptionAtRest: 400 (request "Bad Request") The required attribute accessKeyID was not specified.

  on atlas-encryption.tf line 1, in resource "mongodbatlas_encryption_at_rest" "test":
   1: resource "mongodbatlas_encryption_at_rest" "test" {
```

2020-12-23 07:52 UTC, nikhil-mongo requested changes
Please add the attributes for accesskey and secret key
```
Error: error creating Encryption at Rest: PATCH https://cloud.mongodb.com/api/atlas/v1.0/groups/5dd0f66379358e17e49d6c40/encryptionAtRest: 400 (request "Bad Request") The required attribute accessKeyID was not specified.

  on atlas-encryption.tf line 1, in resource "mongodbatlas_encryption_at_rest" "test":
   1: resource "mongodbatlas_encryption_at_rest" "test" {
```

atlas-encryption.tf
```
resource "mongodbatlas_encryption_at_rest" "test" {
  project_id = var.project_id
  aws_kms = {
    access_key_id = var.access_key
    secret_access_key = var.secret_key
    enabled                = true
    customer_master_key_id = var.customer_master_key
    region                 = var.atlas_region
    role_id = var.cpa_role_id
  }
}
```

2020-12-23 18:29 UTC, coderGo93 commented
Hi @nikhil-mongo , it seems the error is because is not getting the current "version" aka binary, if you don't indicate to use certain version locally it will get from terraform website which is not updated/released yet, so in order to use locally you need to generate the binary first with `go install` then specify in tf to use locally hence the commented line with version in `versions.tf`, I just updated little in the description, let me know if you have more questions/issues.
PD: Terratest is like if you are using terraform commands in terminal kinda different for acceptance test since it can always use the current version(binary) you are developing but for this case is different and  it seems more useful with terratest

2020-12-24 04:39 UTC, nikhil-mongo commented
@coderGo93 I have developed the provider by cloning the master branch and using it from inside ~/.terraform.d/plugins.
I am able to perform all the operations except this `second-step`, as it is missing the required parameters `access_key_id` and `secret_access_key` as per the file `resource_mongodbatlas_encryption_at_rest.go` line 44-52. I added them to the `atlas-encryption.tf` and was able to complete the deployment. Please update these and then it is good to go.

2020-12-24 04:45 UTC, coderGo93 commented
Understood @nikhil-mongo , will add those attributes then, thank you!!

2020-12-28 03:52 UTC, nikhil-mongo requested changes
@coderGo93 Please run `terraform fmt` in the `second step` directory. Rest LGTM.

2021-01-07 00:45 UTC, themantissa commented
@nikhil-mongo  thank you!  If you are good can you approve this PR?

2021-01-08 15:43 UTC, nikhil-mongo approved these changes
Approved

2021-01-08 23:32 UTC, themantissa requested changes
@coderGo93  so Nik approved the example in the examples directly but there are 1700+ files in this repo.  Can we just do the examples, then do a PR just for the integration-testing add (so if anyone needs the bigger test for IAM they have it) and then ensure there's no provider related code in here (there is currently).

2021-01-08 23:32 UTC, themantissa commented on .github/workflows/automated-test.yml
>        - name: Test
I don't think this should be in the PR.

2021-02-11 18:00 UTC, leofigy approved these changes
LGTM

2021-02-12 01:02 UTC, themantissa approved these changes
LGTM, sorry for the delay on my part!

2021-02-12 03:05 UTC, merged