INTMDB-116: Added paramater ldap auth type for resource and datasource(s) of database user
mongodb/terraform-provider-mongodbatlas pull request #376
Opened 2021-01-08 00:15 UTC by coderGo93

## Description

- Added paramater `ldap_auth_type` for resource and datasource(s) of database user
- Added acceptance test `TestAccResourceMongoDBAtlasDatabaseUser_withLDAPAuthType` and `TestAccResourceMongoDBAtlasDatabaseUser_importLDAPAuthType` for import

Link to any related issue(s):

## Type of change:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update
- [ ] Documentation fix/enhancement

## Required Checklist:

- [ ] I have signed the [MongoDB CLA](https://www.mongodb.com/legal/contributor-agreement)
- [ ] I have read the Terraform contribution guidelines
- [x] I have added tests that prove my fix is effective or that my feature works per HashiCorp requirements
- [x] I have added any necessary documentation (if appropriate)
- [x] I have run make fmt and formatted my code

## Further comments

2021-01-26 00:44 UTC, themantissa requested changes
Thanks!  Mostly docs issues.

2021-01-26 00:44 UTC, themantissa commented on website/docs/d/database_user.html.markdown
> +* `ldap_auth_type` - Method by which the provided username is authenticated.
Some of these, like aws_iam_type have the accepted types and some don't.  Let's include them for ldap here and we'll update the others later - they are at https://docs.atlas.mongodb.com/reference/api/database-users-create-a-user

2021-01-26 00:44 UTC, themantissa commented on website/docs/d/database_users.html.markdown
> +* `ldap_auth_type` - Method by which the provided username is authenticated.
Same comment as above, need the type info

2021-01-26 00:44 UTC, themantissa commented on website/docs/r/database_user.html.markdown
> +  * `USER` - LDAP server authenticates this user through the user's LDAP user. `username` must also be a fully qualified distinguished name, as defined in RFC-2253.
Please include the RFC link from the source docs - https://tools.ietf.org/html/2253

2021-01-26 00:44 UTC, themantissa commented on website/docs/r/database_user.html.markdown
> +  * `NONE` -	Atlas authenticates this user through SCRAM-SHA, not LDAP.
please include the SCRAM-SHA link from the source docs: https://docs.mongodb.com/manual/core/security-scram

2021-01-26 00:44 UTC, themantissa commented on website/docs/r/database_user.html.markdown
> +  * `GROUP` -  LDAP server authenticates this user using their LDAP user and authorizes this user using their LDAP group.
Please include the rest of the docs content here: https://docs.atlas.mongodb.com/reference/api/database-users-create-a-user

2021-02-04 23:52 UTC, themantissa approved these changes
LGTM!  Still needs a DoU review.  Also let's hold off on merging till we also get #379 all done and approved as they go together.

2021-02-23 00:32 UTC, leofigy commented on mongodbatlas/resource_mongodbatlas_database_user.go
> +				ValidateFunc: validation.StringInSlice([]string{"NONE", "USER", "GROUP"}, false),
looks good to me, just one test, create user let's say x509_type. and perform a refresh of the provider to the one that has this feature. 

I would expect to only see an in-place update, and no other complain from terraform

2021-02-23 00:32 UTC, leofigy approved these changes

2021-02-23 18:54 UTC, merged