Create 0.8.0-upgrade-guide.html.markdown
mongodb/terraform-provider-mongodbatlas pull request #384
Opened 2021-01-19 22:04 UTC by themantissa

## Description

Guide for IAM creds/roles switch needs and private link deprecation

Link to any related issue(s):

## Type of change:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ x] Documentation fix/enhancement

## Required Checklist:

- [ ] I have signed the [MongoDB CLA](https://www.mongodb.com/legal/contributor-agreement)
- [ ] I have read the Terraform contribution guidelines
- [ ] I have added tests that prove my fix is effective or that my feature works per HashiCorp requirements
- [ ] I have added any necessary documentation (if appropriate)
- [ ] I have run make fmt and formatted my code

## Further comments

2021-01-19 22:21 UTC, leofigy approved these changes
LGTM, Hi @coderGo93 , could you please check as well.

2021-01-19 23:12 UTC, coderGo93 approved these changes
LGTM!

2021-01-20 14:39 UTC, shum requested changes
Minor changes suggested! Looks good!

2021-01-20 14:39 UTC, shum commented on website/docs/guides/0.8.0-upgrade-guide.html.markdown
> +If you programmatically create new Atlas projects and use AWS KMS encryption keys for encryption at rest or you are ready to switch an existing Atlas project using AWS KMS encryption keys for encrypt
Might recommend breaking up the steps into a numbered list for readabilty, eg:
```
Configuring cloud provider access with Terraform is a multi step process:
1. Configure and apply the Atlas `cloud_provider_access` resource // note there was a typo here for "provider"
2. Modify your AWS IAM role trust policy with AWS
3. Add the IAM Assumed Role ARN to your Atlas resource definition
4. Apply again to authorize.
```

2021-01-20 14:39 UTC, shum commented on website/docs/guides/0.8.0-upgrade-guide.html.markdown
> +**Example 1st Terraform Apply**
This doesn't seem to be rendering properly - Github is just squashing all the newlines and making this section hard to read. (Might be Github thing) Consider adding ` ``` ` around the section? 

![Uploading Screen Shot 2021-01-20 at 10.31.32 PM.png…]()

2021-01-20 14:39 UTC, shum commented on website/docs/guides/0.8.0-upgrade-guide.html.markdown
> +    #Information you’ll need to enable encryption at rest later
```suggestion
    #Information you’ll need to enable BYOK encryption at rest later
```

2021-01-20 14:39 UTC, shum commented on website/docs/guides/0.8.0-upgrade-guide.html.markdown
> +    #Information you’ll need to enable encryption at rest later
```suggestion
    #Information you’ll need to enable BYOK encryption at rest later
```

2021-01-20 14:39 UTC, shum commented on website/docs/guides/0.8.0-upgrade-guide.html.markdown
> +    resource "mongodbatlas_cloud_provider_access" "test" {
Same as above re preformatted text.

2021-01-20 14:39 UTC, shum commented on website/docs/guides/0.8.0-upgrade-guide.html.markdown
> +    aws_kms = {
Same as above re preformatted text.

2021-01-20 14:39 UTC, shum commented on website/docs/guides/0.8.0-upgrade-guide.html.markdown
> +      }
Same as above re preformatted text.

2021-01-20 19:39 UTC, shum approved these changes
tiny things. LGTM!!

2021-01-20 19:39 UTC, shum commented on website/docs/guides/0.8.0-upgrade-guide.html.markdown
> +After this process you can then configure or update encryption at rest for your project.  For example:
This line's showing up weird (gets swallowed into the list). Maybe add one extra new line after the list.

2021-01-20 19:39 UTC, shum commented on website/docs/guides/0.8.0-upgrade-guide.html.markdown
> +Mongodbatlas_privatelink_endpoint_service.test {project_id}--{private_link_id}--{endpoint_service_id}--{provider_name}
```suggestion
terraform import mongodbatlas_privatelink_endpoint.test {project_id}-{private_link_id}-{provider_name}
Mongodbatlas_privatelink_endpoint_service.test {project_id}--{private_link_id}--{endpoint_service_id}--{provider_name}
```
hah can't add additional ` ``` `s but we should probably wrap this block too.

2021-01-20 19:59 UTC, merged