NTMDB-163: Wrong order for PrivateLink Endpoint Service and detects unnecessary changes
mongodb/terraform-provider-mongodbatlas pull request #388
Opened 2021-01-23 03:14 UTC by coderGo93

## Description

Private Endpoint (deprecated)
- Added provider name and region in state id for import and read so it won't detect the unnecessary changes for region/provider name while plan after import
Private Endpoint Interface (deprecated)
- Set the fields private link id and interface id in read so it can't detect unnecessary changes.
PrivateLink Endpoint 
- Added region in state id for import and other func(create, read and delete) so it it won't detect the unnecessary changes for region
PrivateLink Endpoint Service
- Changed the wrong order, the field `private_link_id` was using with `endpoint_service_id` information instead of `private_link_id` from private_link_endpoint resource and vice versa(`endpoint_service_id` using with `private_link_id` info)
-  Set the fields private link id in read so it won't detect unnecessary changes.

Link to any related issue(s):

## Type of change:

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update
- [x] Documentation fix/enhancement

## Required Checklist:

- [ ] I have signed the [MongoDB CLA](https://www.mongodb.com/legal/contributor-agreement)
- [ ] I have read the Terraform contribution guidelines
- [x] I have added tests that prove my fix is effective or that my feature works per HashiCorp requirements
- [x] I have added any necessary documentation (if appropriate)
- [x] I have run make fmt and formatted my code

## Further comments

2021-01-23 18:19 UTC, leofigy commented
LGTM, but before merging can you test the manually upgrade. in order to update the documentation steps. 

- Create one template with the deprecated resources using the V0.7.0
- Update the terraform provider to build that contains this terraform fix
- Perform the import procedure 
- At the end do a terraform plan, there should be no changes

Thanks in advance

2021-01-23 18:19 UTC, leofigy approved these changes

2021-01-25 23:49 UTC, themantissa requested changes
LGTM!  Only change would be to ask if you could also update the import examples in the guide: https://github.com/mongodb/terraform-provider-mongodbatlas/blob/master/website/docs/guides/0.8.0-upgrade-guide.html.markdown so that we we get the whole fix in one PR?  Thank you!

2021-01-26 00:54 UTC, themantissa approved these changes
Thanks for adding the guide.

2021-01-26 03:33 UTC, merged

2021-01-26 18:55 UTC, Dani-Relic commented
Hi, what's the estimation for releasing this fix

2021-01-26 19:28 UTC, themantissa commented
@Dani-Relic we have one more bug to fix and then will get it out, should be soon.

2021-01-28 18:31 UTC, RalphBragg commented
Can't wait!

2021-01-28 21:09 UTC, themantissa commented
@RalphBragg @Dani-Relic v0.8.1 is out with this fix.