INTMDB-154: WIP deprecation for provider_encrypt_ebs_volume
mongodb/terraform-provider-mongodbatlas pull request #403
Opened 2021-02-04 05:36 UTC by leofigy

## Description

Now by default all EBS volumes will be encrypted by default, so the option to disable it is being deprecated. 

Link to any related issue(s):

## Type of change:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [X] This change requires a documentation update
- [ ] Documentation fix/enhancement

## Required Checklist:

- [X] I have signed the [MongoDB CLA](https://www.mongodb.com/legal/contributor-agreement)
- [X] I have read the Terraform contribution guidelines
- [X] I have added tests that prove my fix is effective or that my feature works per HashiCorp requirements
- [X] I have added any necessary documentation (if appropriate)
- [X] I have run make fmt and formatted my code

## Further comments

2021-02-12 00:56 UTC, themantissa commented
Just to note "Now by default all EBS volumes will be encrypted by default, so the option to disable it is being deprecated." - This has always been the case but I think it the past one could set it to false and that is no longer the case.  Just an important bit of clarification for anyone looking

2021-02-12 00:59 UTC, themantissa requested changes
Really nice, just one suggested wording change on the deprecation notice and this is ready.  Thank you!

2021-02-12 00:59 UTC, themantissa commented on mongodbatlas/resource_mongodbatlas_cluster.go
> +				Deprecated: "All EBS volumes are now encrypted by default, no option to have encryption disabled",
Let's change this a bit to reduce confusion: 
"All EBS volumes are encrypted by default, the option to disable encryption has been removed",

2021-02-16 23:06 UTC, themantissa approved these changes
Thanks for the small fix!  LGTM!

2021-02-18 21:03 UTC, coderGo93 approved these changes
If all tests works then LGTM!

2021-02-18 21:19 UTC, merged