Examples of terratest upgrade
mongodb/terraform-provider-mongodbatlas pull request #431
Opened 2021-04-08 22:21 UTC by coderGo93

## Description

Added examples of terratest for upgrades tests to see if it works.
First step create the resource with the old version (0.8.2) and then import in another folder with recent plugin and run again terraform plan to see if it works.
Terratests:
- TestUpgradeNetworkContainerRegionsGCP
- TestUpgradeDatabaseUserLDAPAuthType
- TestUpgradeClusterDeprecationEBSVolume

Link to any related issue(s):
INTMDB-189
## Type of change:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Documentation fix/enhancement

## Required Checklist:

- [ ] I have signed the [MongoDB CLA](https://www.mongodb.com/legal/contributor-agreement)
- [ ] I have read the Terraform contribution guidelines
- [ ] I have added tests that prove my fix is effective or that my feature works per HashiCorp requirements
- [ ] I have added any necessary documentation (if appropriate)
- [ ] I have run make fmt and formatted my code

## Further comments

2021-04-09 02:17 UTC, leofigy commented on examples/test-upgrade/cluster/old/.terraform.lock.hcl
> +provider "registry.terraform.io/mongodb/mongodbatlas" {
you could add this to git ignore

2021-04-09 02:22 UTC, leofigy requested changes
The source files for this testing can be in a different path instead of
**examples/test-upgrade/cluster/**
could be at 
**integration-testing/upgrade/v090/**cluster/

2021-04-14 20:52 UTC, themantissa requested changes
Just a few things similar to Angel.   Overall looks good and hoping this catches issues faster!  Thanks.

2021-04-14 20:52 UTC, themantissa commented on examples/test-upgrade/cluster/old/main.tf
> +resource "mongodbatlas_project" "test" {
Instead of old and updated can we do version numbers?   Will be more sustainable I think over time.

2021-04-14 20:52 UTC, themantissa commented on examples/test-upgrade/cluster/old/main.tf
> +  mongo_db_major_version       = "4.0"
Just an FYI but we should get in the habit of changing these to the latest version of MDB, currently 4.4.   5.0 will come this summer.

2021-04-14 20:52 UTC, themantissa commented on examples/test-upgrade/database-user/old/.terraform.lock.hcl
> +# This file is maintained automatically by "terraform init".
Similar to above comment from Angel - should ignore these.

2021-04-20 00:21 UTC, themantissa commented
@coderGo93  I just got a ping to review but I don't see any changes?

2021-04-20 00:22 UTC, leofigy approved these changes
LGTM now :) , maybe a sync issue, because the commit of the PR appeared with a delay

2021-04-20 00:24 UTC, coderGo93 commented
@themantissa I made a mistake but I just pushed changes

2021-04-20 00:28 UTC, themantissa approved these changes
LGTM, thank you!  The naming is much clearer!

2021-04-20 00:33 UTC, merged