INTMDB-199: Fixes the error when updating an replication specs after removed one zone
mongodb/terraform-provider-mongodbatlas pull request #434
Opened 2021-04-16 16:48 UTC by coderGo93

## Description
Changed to TypeSet for `replication_specs` schema, added a validation to compare the zone name if it's the same for old and new values and the get the ID generated from original object and set it in request for update to avoid an error like `Updating id of existing replication spec`

Link to any related issue(s):

## Type of change:

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Documentation fix/enhancement

## Required Checklist:

- [ ] I have signed the [MongoDB CLA](https://www.mongodb.com/legal/contributor-agreement)
- [ ] I have read the Terraform contribution guidelines
- [ ] I have added tests that prove my fix is effective or that my feature works per HashiCorp requirements
- [ ] I have added any necessary documentation (if appropriate)
- [x] I have run make fmt and formatted my code

## Further comments

2021-04-19 20:07 UTC, themantissa approved these changes
LGTM, @leofigy please review to ensure this covers INTMDB-199.  I think so but want to be sure.  Thanks!

2021-04-20 06:33 UTC, leofigy commented
Hello @themantissa , @coderGo93 

After spending a while, I think we must roll back the type to an array, instead of a Set. 
I know the diff is awful, but we're taking care finding the IDs to fix the patch request. 

I played with Set, but the type is even worse because it generates a diff everytime because the computed attributed even if you only change the order and the items remain the same, it seems the hash is not that good. 

I was trying to see if we could skip using DiffSuppressFunc. but it didn't work because does not evaluate the composed attribute at the top :(

2021-04-20 06:38 UTC, leofigy requested changes
Hello please rollback to use the TypeList, and just make sure we keep retaining the ID

2021-04-20 16:30 UTC, leofigy approved these changes
LGTM thanks

2021-04-20 18:25 UTC, themantissa commented
Just ack'ing that I still approve with the 2nd commit with new changes.  Thank you

2021-04-20 19:15 UTC, merged