updated cluster doc and examples  for the new IOPS change
mongodb/terraform-provider-mongodbatlas pull request #446
Opened 2021-04-26 07:11 UTC by nikhil-mongo

## Description

updated cluster doc for the new IOPS change and removed the IOPS config from examples so that they are launched with the default configuration of 3000 IOPS

Link to any related issue(s):

## Type of change:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [x] Documentation fix/enhancement

## Required Checklist:

- [ ] I have signed the [MongoDB CLA](https://www.mongodb.com/legal/contributor-agreement)
- [ ] I have read the Terraform contribution guidelines
- [ ] I have added tests that prove my fix is effective or that my feature works per HashiCorp requirements
- [x] I have added any necessary documentation (if appropriate)
- [x] I have run make fmt and formatted my code

## Further comments

2021-04-26 16:07 UTC, themantissa requested changes
A few comments in line, thank you for doing this.

2021-04-26 16:07 UTC, themantissa commented on website/docs/r/cluster.html.markdown
> +  * The default IOPS value for the AWS clusters is now 3000 upto 1TB standard EBS storage. You do not need to configure IOPS for the Standard EBS configuration.
We should not add all of this - as noted above they should view in the Atlas console as we can't keep up with changes in a human generated fashion in docs right now.   
If you want to add "You do not need to configure IOPS for a STANDARD disk configuration but only for a PROVISIONED configuration. " I think that would make sense.

2021-04-26 16:07 UTC, themantissa commented on examples/starter/atlas_cluster.tf
>    provider_volume_type         = "STANDARD"
remove provider_volume_type as it's not needed

2021-04-26 16:07 UTC, themantissa commented on examples/aws-atlas-privatelink/atlas-cluster.tf
>    provider_volume_type        = "STANDARD"
remove as not needed: provider_volume_type

2021-04-26 16:07 UTC, themantissa commented on examples/Atlas_Database_Users/atlas_cluster.tf
>    provider_volume_type         = "STANDARD"
Remove as not needed.

2021-04-27 12:27 UTC, nikhil-mongo commented
@themantissa the changes have been made.

2021-04-27 15:48 UTC, themantissa approved these changes
Great job, thank you @nikhil-mongo !

2021-04-27 15:48 UTC, merged