INTMDB-208: Updated docs for upgrading private endpoints
mongodb/terraform-provider-mongodbatlas pull request #458
Opened 2021-05-12 17:56 UTC by coderGo93

## Description

- Added terratest for upgrading with resources `mongodbatlas_private_endpoint` and `mongodbatlas_private_endpoint_interface_link`
- Updated docs for guide upgrading v0.9.1
- Added validation where it should run make testacc if there's changes for folder mongodbatlas/ and should not run for changes inside folder website/docs

Link to any related issue(s):

## Type of change:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Documentation fix/enhancement

## Required Checklist:

- [ ] I have signed the [MongoDB CLA](https://www.mongodb.com/legal/contributor-agreement)
- [ ] I have read the Terraform contribution guidelines
- [x] I have added tests that prove my fix is effective or that my feature works per HashiCorp requirements
- [ ] I have added any necessary documentation (if appropriate)
- [ ] I have run make fmt and formatted my code

## Further comments

2021-05-12 19:07 UTC, leofigy commented on website/docs/guides/0.9.1-upgrade-guide.html.markdown
> +2. Change the version of provider to the newest version
Let's say the version 0.9.1 , because in theory for v1 because is a major version old deprecated resources should be removed finally

2021-05-12 19:08 UTC, leofigy approved these changes
LGTM !

2021-05-12 20:45 UTC, themantissa requested changes
Just a small improvement to link to the new resources, otherwise LGTM.

2021-05-12 20:45 UTC, themantissa commented on website/docs/guides/0.9.1-upgrade-guide.html.markdown
> +Warning: this resource is deprecated, please transition as soon as possible to mongodbatlas_privatelink_endpoint
Can we get a docs link to mongodbatlas_privatelink_endpoint on the phrase "mongodbatlas_privatelink_endpoint"

2021-05-12 20:45 UTC, themantissa commented on website/docs/guides/0.9.1-upgrade-guide.html.markdown
> +Warning: this resource is deprecated, please transition as soon as possible to mongodbatlas_privatelink_endpoint_service
Can we get a docs link to mongodbatlas_privatelink_endpoint_service on the phrase "mongodbatlas_privatelink_endpoint_service"

2021-05-13 17:09 UTC, themantissa approved these changes
LGTM!

2021-05-13 17:35 UTC, merged