INTMDB-215: tag version 1.0.0 for pre-release
mongodb/terraform-provider-mongodbatlas pull request #508
Opened 2021-08-06 21:54 UTC by coderGo93

## Description

Please include a summary of the fix/feature/change, including any relevant motivation and context.

Link to any related issue(s):

## Type of change:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Documentation fix/enhancement

## Required Checklist:

- [ ] I have signed the [MongoDB CLA](https://www.mongodb.com/legal/contributor-agreement)
- [ ] I have read the Terraform contribution guidelines
- [ ] I have added tests that prove my fix is effective or that my feature works per HashiCorp requirements
- [ ] I have added any necessary documentation (if appropriate)
- [ ] I have run make fmt and formatted my code

## Further comments

2021-08-09 23:10 UTC, themantissa requested changes
This doesn't seem inline with how we've done the -pre releases before.   Are you changing the process? If so why?

2021-08-09 23:10 UTC, themantissa commented on CHANGELOG.md
> +[Full Changelog](https://github.com/mongodb/terraform-provider-mongodbatlas/compare/v0.9.1...HEAD)
This doesn't seem in line with how we've done this before.  Before it would point to the new version but with the -pre before we released, then show the final.  This seems like it's skipping that step: e.g.: 
 [Full Changelog](https://github.com/mongodb/terraform-provider-mongodbatlas/compare/v0.9.1-pre.1...v0.9.1)

2021-08-09 23:20 UTC, coderGo93 commented on CHANGELOG.md
> +[Full Changelog](https://github.com/mongodb/terraform-provider-mongodbatlas/compare/v0.9.1...HEAD)
I did not realize that part, will change that, thank you melissa

2021-08-09 23:44 UTC, themantissa approved these changes
lgtm

2021-08-10 00:05 UTC, thetonymaster approved these changes

2021-08-10 00:28 UTC, merged