INTMDB-244: add deprecation notes for cloud backup documentation
mongodb/terraform-provider-mongodbatlas pull request #525
Opened 2021-08-24 20:03 UTC by abner-dou

## Description

Marked some resources and datasources as deprecated, also cluster documentation was updated

Link to any related issue(s):

## Type of change:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [x] Documentation fix/enhancement

## Required Checklist:

- [x] I have signed the [MongoDB CLA](https://www.mongodb.com/legal/contributor-agreement)
- [ ] I have read the Terraform contribution guidelines
- [ ] I have added tests that prove my fix is effective or that my feature works per HashiCorp requirements
- [x] I have added any necessary documentation (if appropriate)
- [ ] I have run make fmt and formatted my code

## Further comments

2021-08-24 20:28 UTC, themantissa requested changes
In all the examples for cluster in other resources did you check for  provider_backup_enabled      = true and replace it?   I'm pretty sure there's a bunch out there a simple find and replace should fix.  Other issues are noted inline.

2021-08-24 20:28 UTC, themantissa commented on website/docs/d/cluster.html.markdown
> +  cloud_backup_config           = true
Which is it?  In @coderGo93's add to the guide it states: 
IMPORTANT In resource mongodbatlas_cluster the parameter provider_backup_enabled has been deprecated, use cloud_backup instead.
Now this has cloud_backup_config.   Looks like cloud_backup: https://github.com/mongodb/terraform-provider-mongodbatlas/blob/master/mongodbatlas/resource_mongodbatlas_cluster.go#L151.  Looking at rest maybe a typo?

2021-08-24 20:28 UTC, themantissa commented on website/docs/r/cluster.html.markdown
>  ### Cloud Backup Policy
The entire goal of the rework of the cloud backup policy was to remove this once people transitioned to the better resource  - this section should all be marked deprecated.   While the policy is still added it is only needed for the old cloud_provider_snapshot_backup_policy.html.markdown  so we should make that clear here.   @coderGo93 and @thetonymaster since it seems a person who did not work on this is now trying to update the documentation and may not have the full picture you need to help him out.

2021-08-24 20:30 UTC, abner-dou commented on website/docs/d/cluster.html.markdown
> +  cloud_backup_config           = true
this was a typo (autocomplete feature don't help me in this)

2021-08-24 20:31 UTC, coderGo93 commented on website/docs/d/cluster.html.markdown
> +  cloud_backup_config           = true
Yes, it seems its a typo, it should be `cloud_backup`

2021-08-25 09:27 UTC, gssbzn commented on website/docs/r/cluster.html.markdown
> +    * Any net new Atlas clusters of any type do not support this parameter. These clusters must use Cloud Backup, `cloud_backup`, to enable Cloud Backup.  If you create a new Atlas cluster and set `b
```suggestion
    * New Atlas clusters of any type do not support this parameter. These clusters must use Cloud Backup, `cloud_backup`, to enable Cloud Backup.  If you create a new Atlas cluster and set `backup_enabled` to true, the Provider will respond with an error.  This change doesn’t affect existing clusters that use legacy backups.
```

2021-08-25 09:54 UTC, gssbzn approved these changes
From my side LGTM with one small improvement to the copy, @themantissa point may still need to be addressed but I also don't have full context here

2021-08-25 18:18 UTC, abner-dou commented on website/docs/r/cluster.html.markdown
>  ### Cloud Backup Policy
@coderGo93 @thetonymaster acording to this comment, can you give me more context about how I must deprecate this part?

2021-08-25 19:22 UTC, thetonymaster commented on website/docs/r/cluster.html.markdown
>  ### Cloud Backup Policy
Set a meeting with @coderGo93

2021-08-25 21:31 UTC, abner-dou commented on website/docs/r/cluster.html.markdown
> +    * Any net new Atlas clusters of any type do not support this parameter. These clusters must use Cloud Backup, `cloud_backup`, to enable Cloud Backup.  If you create a new Atlas cluster and set `b
I already fixed this :D

2021-08-25 22:48 UTC, themantissa requested changes
Very close, just a slight change in wording to make it deprecated now vs in the future.

2021-08-25 22:48 UTC, themantissa commented on website/docs/d/cluster.html.markdown
> +**WARNING:** This property is going to be deprecated, use `mongodbatlas_cloud_backup_schedule` datasource instead.
Technically this is deprecated, the next step is removal.  So the correct wording should be for all instances in the PR: 
**WARNING:** This property is deprecated, use `mongodbatlas_cloud_backup_schedule` datasource instead.

2021-08-25 22:51 UTC, abner-dou commented on website/docs/d/cluster.html.markdown
> +**WARNING:** This property is going to be deprecated, use `mongodbatlas_cloud_backup_schedule` datasource instead.
change already done :D

2021-08-25 23:01 UTC, themantissa commented on website/docs/d/cluster.html.markdown
> +**WARNING:** This property is going to be deprecated, use `mongodbatlas_cloud_backup_schedule` datasource instead.
Like a ninja!  TY!

2021-08-25 23:03 UTC, themantissa approved these changes
LGTM!

2021-08-26 15:33 UTC, thetonymaster approved these changes

2021-08-26 16:11 UTC, abner-dou commented
@themantissa this PR is ready to merge :)

2021-08-26 17:12 UTC, merged