INTMDB-216: Added resource and datasource(s) of Advanced Cluster
mongodb/terraform-provider-mongodbatlas pull request #570
Opened 2021-09-23 20:46 UTC by coderGo93

## Description

- Added resource and datasource(s) of [Advanced Cluster](https://docs.atlas.mongodb.com/reference/api/cluster-advanced/create-one-cluster-advanced/)
- Added tests for resource and datasource(s)
- Added docs for resource and datasource(s)

Link to any related issue(s):

## Type of change:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update
- [ ] Documentation fix/enhancement

## Required Checklist:

- [ ] I have signed the [MongoDB CLA](https://www.mongodb.com/legal/contributor-agreement)
- [ ] I have read the Terraform contribution guidelines
- [x] I have added tests that prove my fix is effective or that my feature works per HashiCorp requirements
- [x] I have added any necessary documentation (if appropriate)
- [x] I have run make fmt and formatted my code

## Further comments
Awaiting for the [merge](https://github.com/mongodb/go-client-mongodb-atlas/pull/258) then update the client vendor

2021-09-25 00:24 UTC, themantissa commented
@coderGo93 fyi tests have failed.

2021-09-27 16:04 UTC, coderGo93 commented
Hi @themantissa, yes it's expected to fail because of a field not being available but the [PR](https://github.com/mongodb/go-client-mongodb-atlas/pull/258) of client is not merged yet.

2021-10-11 20:47 UTC, thetonymaster approved these changes

2021-10-14 08:08 UTC, andreaangiolillo approved these changes
LGTM

2021-10-20 23:20 UTC, themantissa requested changes
I'd like to see a better test suite to hopefully catch more potential bugs.   Also would like to see more care to the documentation and ensuring it reflects the source material.  fyi @jwilliams-mongo  I'll likely add you for another docs review after this gets some improvement.

2021-10-20 23:20 UTC, themantissa commented on mongodbatlas/data_source_mongodbatlas_advanced_cluster_test.go
> +      provider_name         = "TENANT"
This is not enough test coverage.   TENANT is our shared cluster tier - the most basic offering we have.  Testing for it is fine but not enough.  Most who use Advanced Clusters, especially at first, will be using it to create multi-cloud clusters; meaning a replica set or sharded clusters that spans multiple cloud providers - e.g. 3 notes in AWS, 2 in Azure.    Our tests should cover this for both data sources and resources.

2021-10-20 23:20 UTC, themantissa commented on mongodbatlas/resource_mongodbatlas_advanced_cluster.go
> +
We have the catches and docs but I don't see anywhere where you set the actual value Infrastructure Tool like in clusters? 
https://github.com/mongodb/terraform-provider-mongodbatlas/blob/master/mongodbatlas/resource_mongodbatlas_cluster.go#L34

2021-10-20 23:20 UTC, themantissa commented on mongodbatlas/resource_mongodbatlas_advanced_cluster.go
> +		Schema: map[string]*schema.Schema{
Just to check, I'm assuming this is a copy of the existing clusters resource with just the relevant changes made?  So if a bug happens in clusters it will likely happen, and need to be checked for, here?

2021-10-20 23:20 UTC, themantissa commented on mongodbatlas/resource_mongodbatlas_advanced_cluster_test.go
> +func testAccMongoDBAtlasAdvancedClusterConfigMultiCloud(projectID, name string) string {
Again I'd like to see way more test coverage to catch more issues.   Having the multi-provider test is good but we should step through:
Creating a single provider cluster and a multi-provider cluster
Upgrading an existing single provider cluster to a multi-provider
At least creating sharded, multi-provider cluster. 
Destroying them all.

2021-10-20 23:20 UTC, themantissa commented on website/docs/r/advanced_cluster.html.markdown
> +
Overall it feels like this and data sources was copied form the existing clusters and the new info added.   That's a good way to start but let's take this opportunity to update all the information to be most updated to the source - https://docs.atlas.mongodb.com/reference/api/cluster-advanced/create-one-cluster-advanced/.   

This is also missing all the new information at the top of: https://docs.atlas.mongodb.com/reference/api/cluster-advanced/create-one-cluster-advanced/. Let's make sure this and datasources contains all the relevant information.

2021-10-20 23:20 UTC, themantissa commented on website/docs/r/advanced_cluster.html.markdown
> +
Please add a non multicloud example, e.g. single region, single provider. 
resource "mongodbatlas_advanced_cluster" "test" {
  project_id   = "%[1]q"
  name         = "%[2]q"
  cluster_type = "REPLICASET"
  replication_specs {
    region_configs {
      electable_specs {
        instance_size = "M10"
        node_count    = 3
      }
      analytics_specs {
        instance_size = "M10"
        node_count    = 1
      }
      provider_name = "AWS"
      priority      = 1
      region_name   = "US_EAST_1"
    }
  }
}

2021-10-20 23:20 UTC, themantissa commented on website/docs/r/advanced_cluster.html.markdown
> +  Shared Cluster Backups for tenant clusters.
These are missing the important links from https://docs.atlas.mongodb.com/reference/api/cluster-advanced/create-one-cluster-advanced/

2021-10-20 23:20 UTC, themantissa commented on website/docs/r/advanced_cluster.html.markdown
> +* `disk_size_gb` - (Optional) Capacity, in gigabytes, of the host's root volume. Increase this number to add capacity, up to a maximum possible value of 4096 (i.e., 4 TB). This value must be a positi
Missing some of the links from the documentation (like to NVMe and upgrading your clusters) https://docs.atlas.mongodb.com/reference/api/cluster-advanced/create-one-cluster-advanced/

2021-10-20 23:20 UTC, themantissa commented on website/docs/r/advanced_cluster.html.markdown
> +* `encryption_at_rest_provider` - (Optional) Possible values are AWS, GCP, AZURE or NONE.  Only needed if you desire to manage the keys, see [Encryption at Rest using Customer Key Management](https:/
This needs updating from the source doc https://docs.atlas.mongodb.com/reference/api/cluster-advanced/create-one-cluster-advanced/

2021-10-20 23:20 UTC, themantissa commented on website/docs/r/advanced_cluster.html.markdown
> +* `labels` - (Optional) Configuration for the collection of key-value pairs that tag and categorize the cluster. See below.
Says see below but not very helpful directionally.  Can we either link to it or add the info here?

2021-10-20 23:20 UTC, themantissa commented on website/docs/r/advanced_cluster.html.markdown
> +* `mongo_db_major_version` - (Optional) Version of the cluster to deploy. Atlas supports the following MongoDB versions for M10+ clusters: `3.6`, `4.0`, `4.2` or `4.4`.
Missing a lot of content from https://docs.atlas.mongodb.com/reference/api/cluster-advanced/create-one-cluster-advanced/.

2021-10-21 19:22 UTC, coderGo93 commented on mongodbatlas/data_source_mongodbatlas_advanced_cluster_test.go
> +      provider_name         = "TENANT"
Understood, will implement the similar tests of resource in datasource

2021-10-21 19:28 UTC, coderGo93 commented on mongodbatlas/resource_mongodbatlas_advanced_cluster.go
> +		Schema: map[string]*schema.Schema{
Something like that, some parameters are the same as the cluster resource in schema, in cluster many deprecated parameters because of Type like `bi_connector` or similar for request, but some parameters has the same info in response like the parameter `connection_strings`.

2021-10-21 19:29 UTC, coderGo93 commented on mongodbatlas/resource_mongodbatlas_advanced_cluster_test.go
> +func testAccMongoDBAtlasAdvancedClusterConfigMultiCloud(projectID, name string) string {
Understood, will add more test coverage, thank you, Melissa.

2021-10-21 20:16 UTC, coderGo93 commented on mongodbatlas/resource_mongodbatlas_advanced_cluster.go
> +
I'm not sure what do you mean, it's reusing the same variable(`defaultLabel`) from the cluster in advanced clusters resources/datasource.

2021-10-26 23:15 UTC, themantissa commented on mongodbatlas/resource_mongodbatlas_advanced_cluster.go
> +		Schema: map[string]*schema.Schema{
Let's just be sure if we have a bug going forward in clusters we can likely assume it will be in advanced clusters and address it accordingly. Can you share w/ the DoU team?

2021-10-26 23:17 UTC, themantissa commented on mongodbatlas/resource_mongodbatlas_advanced_cluster.go
> +
But where are you setting it?   We set the Infrastructure Tool label in clusters and we should do the same for advanced clusters, does that make more sense?

2021-10-26 23:23 UTC, themantissa requested changes
Almost there.  One docs add and tried to clarify my point on Infrastructure Tools (these clusters should have that label set)

2021-10-26 23:23 UTC, themantissa commented on website/docs/r/advanced_cluster.html.markdown
> +
More information on considerations for using advanced clusters please see https://docs.atlas.mongodb.com/reference/api/cluster-advanced/create-one-cluster-advanced/#considerations

2021-10-26 23:23 UTC, themantissa commented on website/docs/r/advanced_cluster.html.markdown
> +
This is still missing the considerations. Can you add the sentence I put below w/ a link back to the primary docs?

2021-10-27 16:14 UTC, coderGo93 commented on mongodbatlas/resource_mongodbatlas_advanced_cluster.go
> +
In resource, there are reusing in some lines like [L308](https://github.com/mongodb/terraform-provider-mongodbatlas/blob/fe174447afdee77a969829fdf957b2bfd64b6eb9/mongodbatlas/resource_mongodbatlas_advanced_cluster.go#L308), [L407](https://github.com/mongodb/terraform-provider-mongodbatlas/blob/fe174447afdee77a969829fdf957b2bfd64b6eb9/mongodbatlas/resource_mongodbatlas_advanced_cluster.go#L407), [L480](https://github.com/mongodb/terraform-provider-mongodbatlas/blob/fe174447afdee77a969829fdf957b2bfd64b6eb9/mongodbatlas/resource_mongodbatlas_advanced_cluster.go#L480).
In datasource, in [L231](https://github.com/mongodb/terraform-provider-mongodbatlas/blob/fe174447afdee77a969829fdf957b2bfd64b6eb9/mongodbatlas/data_source_mongodbatlas_advanced_cluster.go#L231)

2021-10-27 20:25 UTC, coderGo93 commented on website/docs/r/advanced_cluster.html.markdown
> +
Added

2021-10-27 20:31 UTC, coderGo93 commented on mongodbatlas/resource_mongodbatlas_advanced_cluster.go
> +		Schema: map[string]*schema.Schema{
Understood, yeah it's possible to have a bug in advanced cluster if the parameter affected or behavior is the same as the cluster or something like that.

2021-10-27 23:29 UTC, themantissa commented on mongodbatlas/resource_mongodbatlas_advanced_cluster.go
> +
Ah, I missed 308.  Thank you

2021-10-27 23:29 UTC, themantissa approved these changes

2021-10-28 12:20 UTC, merged