INTMDB-239: Added new resource/datasource and deprecate for cloud backup snapshot and restore job
mongodb/terraform-provider-mongodbatlas pull request #581
Opened 2021-10-08 16:04 UTC by coderGo93

## Description

- Added resources for Cloud backup snapshot (`mongodbatlas_cloud_backup_snapshot`) and Cloud backup snapshot restore job(`mongodbatlas_cloud_backup_snapshot_restore_job`)
- Added data sources for Cloud backup snapshot (`mongodbatlas_cloud_backup_snapshot` and `mongodbatlas_cloud_backup_snapshots`) and Cloud backup snapshot restore job(`mongodbatlas_cloud_backup_snapshot_restore_job` and `mongodbatlas_cloud_backup_snapshot_restore_jobs`)
- Added a terratest to simulate the steps for import from the older version to the latest version
- Deprecated resources for Cloud provider snapshot (`mongodbatlas_cloud_provider_snapshot`) and Cloud provider snapshot restore job(`mongodbatlas_cloud_provider_snapshot_restore_job`)
- Deprecated data sources for Cloud provider snapshot (`mongodbatlas_cloud_provider_snapshot` and `mongodbatlas_cloud_provider_snapshots`) and Cloud provider snapshot restore job(`mongodbatlas_cloud_provider_snapshot_restore_job` and `mongodbatlas_cloud_provider_snapshot_restore_jobs`)

Link to any related issue(s):

## Type of change:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update
- [x] Documentation fix/enhancement

## Required Checklist:

- [ ] I have signed the [MongoDB CLA](https://www.mongodb.com/legal/contributor-agreement)
- [ ] I have read the Terraform contribution guidelines
- [x] I have added tests that prove my fix is effective or that my feature works per HashiCorp requirements
- [x] I have added any necessary documentation (if appropriate)
- [x] I have run make fmt and formatted my code

## Further comments

2021-10-11 08:29 UTC, andreaangiolillo commented on examples/test-upgrade/v110/cloud-backup-snapshot/v102/main.tf
> +  # Provider Settings "block"
What does this comment mean? `# Provider Settings "block"`

2021-10-11 08:29 UTC, andreaangiolillo commented on integrationtesting/test-upgrades_test.go
> +	// Run `terraform apply`. Fail the test if there are any errors.
```suggestion
```

2021-10-11 08:29 UTC, andreaangiolillo commented on mongodbatlas/data_source_mongodbatlas_cloud_backup_snapshot.go
> +)
please, `goimports` the file

2021-10-11 08:29 UTC, andreaangiolillo commented on mongodbatlas/data_source_mongodbatlas_cloud_backup_snapshot.go
> +			"snapshot_id": {
[q] Why are we not providing some of the params that are in [Get One Cloud Backup
](https://docs.atlas.mongodb.com/reference/api/cloud-backup/backup/get-one-backup/) such as `members` or  `snapshotIds`? Those params are returned for shared Clusters

2021-10-11 08:29 UTC, andreaangiolillo commented on mongodbatlas/data_source_mongodbatlas_cloud_backup_snapshot_restore_job.go
> +)
`goimports` file

2021-10-11 08:29 UTC, andreaangiolillo commented on mongodbatlas/data_source_mongodbatlas_cloud_backup_snapshot_restore_jobs.go
> +)
`goimport` file

2021-10-11 08:29 UTC, andreaangiolillo commented on mongodbatlas/data_source_mongodbatlas_cloud_backup_snapshots.go
> +)
goimport file

2021-10-11 08:29 UTC, andreaangiolillo commented on mongodbatlas/resource_mongodbatlas_cloud_backup_snapshot.go
> +	matlas "go.mongodb.org/atlas/mongodbatlas"
goimport file

2021-10-11 08:29 UTC, andreaangiolillo commented on mongodbatlas/resource_mongodbatlas_cloud_backup_snapshot.go
> +		RetentionInDays: d.Get("retention_in_days").(int),
`RetentionInDays` must be at least 1. I would set this to 1 if not provided.

2021-10-11 15:42 UTC, coderGo93 commented on examples/test-upgrade/v110/cloud-backup-snapshot/v102/main.tf
> +  # Provider Settings "block"
A comment for block provider used as a "separator", I can remove it if you want

2021-10-11 15:55 UTC, coderGo93 commented on mongodbatlas/data_source_mongodbatlas_cloud_backup_snapshot.go
> +			"snapshot_id": {
This is just a duplicate of the deprecated but renamed, it seems it wasn't in the deprecated, not sure if it can be added in this ticket since it's not in the scope, should I add them or this is for another ticket? @themantissa

2021-10-11 16:00 UTC, coderGo93 commented on mongodbatlas/resource_mongodbatlas_cloud_backup_snapshot.go
> +		RetentionInDays: d.Get("retention_in_days").(int),
Added validation, thank you

2021-10-11 16:01 UTC, coderGo93 commented on mongodbatlas/data_source_mongodbatlas_cloud_backup_snapshot.go
> +)
done

2021-10-11 16:04 UTC, andreaangiolillo approved these changes
LGTM. A check is failing though.

2021-10-11 20:47 UTC, thetonymaster approved these changes
LGTM just check tests

2021-10-11 22:24 UTC, themantissa commented on mongodbatlas/data_source_mongodbatlas_cloud_backup_snapshot.go
> +			"snapshot_id": {
It's a duplicate but if it's missing params then we should update it when recreating or we just keep bringing issues forward.  It's actually called out in the ticket description "We should double check there are no other changes with these at the same time." but I will add the clarification, "if there are changes, we should update the resource/data source to accommodate them".

2021-10-12 20:37 UTC, coderGo93 commented on mongodbatlas/data_source_mongodbatlas_cloud_backup_snapshot.go
> +			"snapshot_id": {
@themantissa Just pushed changes with the missing params but still waiting for the [PR](https://github.com/mongodb/go-client-mongodb-atlas/pull/261) to be merged, so I can update the vendor and pass the check.

2021-10-13 23:33 UTC, themantissa commented
@coderGo93  do you want to check on why the tests failed?

2021-10-14 00:58 UTC, coderGo93 commented
@themantissa it fails because the [PR](https://github.com/mongodb/go-client-mongodb-atlas/pull/261) is not merged yet so I can update the vendor from the master hence the error of undefined for some parameters

2021-10-21 00:03 UTC, themantissa requested changes
A few small issues to address.

2021-10-21 00:03 UTC, themantissa commented on mongodbatlas/data_source_mongodbatlas_cloud_backup_snapshot.go
> +			"snapshot_id": {
Realized I miss the note here @coderGo93 - feel free to always slack me as well to help get the changes in the go client.   Also, when we deprecate and add a new resource and there are new parameters it is safe to assume new additions are in scope as this will help us keep things updated.  But always feel free to check first.

2021-10-21 00:03 UTC, themantissa commented on mongodbatlas/resource_mongodbatlas_privatelink_endpoint_service.go
>  		return diag.FromErr(fmt.Errorf(errorEndpointSetting, "aws_connection_status", endpointServiceID, err))
This should not be in this PR. Please correct.

2021-10-21 00:03 UTC, themantissa commented on website/docs/guides/1.1.0-upgrade-guide.html.markdown
> +### Remove the existing and import the new resource
I would label this as Option 1 and the other as Option 2, e.g.:
 ### Option 1: Remove the existing and import the new resource

2021-10-21 00:03 UTC, themantissa commented on website/docs/guides/1.1.0-upgrade-guide.html.markdown
> +There are two ways to upgrade from v1.0.2 to v1.1.0 with the existing resources `mongodbatlas_cloud_provider_snapshot_backup_policy`
I would change slightly to make this easier to structure, for example:
There are two possible options to upgrade from v1.0.2 to v1.1.0 from the existing resources `mongodbatlas_cloud_provider_snapshot_backup_policy` to the new ones.

2021-10-21 00:03 UTC, themantissa commented on website/docs/guides/1.1.0-upgrade-guide.html.markdown
> +### Replace the name of resource in terraform state
Add Option 2:

2021-10-21 23:41 UTC, coderGo93 commented on mongodbatlas/resource_mongodbatlas_privatelink_endpoint_service.go
>  		return diag.FromErr(fmt.Errorf(errorEndpointSetting, "aws_connection_status", endpointServiceID, err))
Did you mean the changes related to Status?, if so, I can roll back, but the linter checks  will fail until this [PR](https://github.com/mongodb/terraform-provider-mongodbatlas/pull/586) is merged because of client changes and needs to be updated

2021-10-21 23:44 UTC, coderGo93 commented on website/docs/guides/1.1.0-upgrade-guide.html.markdown
> +### Remove the existing and import the new resource
Updated, thank you

2021-10-26 23:26 UTC, themantissa requested changes
One very small typo in the fix.

2021-10-26 23:26 UTC, themantissa commented on website/docs/guides/1.1.0-upgrade-guide.html.markdown
> +### Option2: Replace the name of resource in terraform state
Missing a space.

2021-10-27 23:30 UTC, themantissa approved these changes
LGTM, thank you!

2021-10-30 14:25 UTC, merged