fixes failing snapshots because timeout is too short
mongodb/terraform-provider-mongodbatlas pull request #583
Opened 2021-10-13 17:41 UTC by ebostijancic

## Description

If the cloud provider snapshot takes longer than 10minutes, terraform apply will fail. This pull request make the timeout configurable.

Link to any related issue(s):

## Type of change:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update
- [x] Documentation fix/enhancement

## Required Checklist:

- [x] I have signed the [MongoDB CLA](https://www.mongodb.com/legal/contributor-agreement)
- [x] I have read the Terraform contribution guidelines
- [x] I have added tests that prove my fix is effective or that my feature works per HashiCorp requirements
- [x] I have added any necessary documentation (if appropriate)
- [ ] I have run make fmt and formatted my code

## Further comments

2021-10-14 08:11 UTC, andreaangiolillo approved these changes
LGTM with a question

2021-10-14 08:11 UTC, andreaangiolillo commented on mongodbatlas/resource_mongodbatlas_cloud_provider_snapshot.go
> +	}
[q] what about the scenarios where `timeout` is set to a negative number or empty string?
[q] why `timeout` is a string and not an interger?

2021-10-14 08:28 UTC, ebostijancic commented
A time duration cannot be negative and it's string because it's defined like: "1h" or "30m". I admit it would be better to be declared as a block see operational timeouts for more information: 

[Terraform Operation Timeouts](https://www.terraform.io/docs/language/resources/syntax.html#operation-timeouts)

2021-10-14 23:32 UTC, themantissa commented on mongodbatlas/resource_mongodbatlas_cloud_provider_snapshot.go
> +			},
If we are including a new option it needs to be added to the documentation as well for the provider.

2021-10-14 23:33 UTC, themantissa requested changes
See comment on docs. Please include that. Thank you!

2021-10-14 23:35 UTC, themantissa commented
@ebostijancic thank you for the submission.   Did you sign the CLA yet?  https://www.mongodb.com/legal/contributor-agreement   We will need that completed before we can merge in the work, once approved.  Thank you!

2021-10-15 06:41 UTC, ebostijancic commented
> @ebostijancic thank you for the submission. Did you sign the CLA yet? https://www.mongodb.com/legal/contributor-agreement We will need that completed before we can merge in the work, once approved. Thank you!

I have signed the CLA and updated the documention

2021-10-17 18:35 UTC, ebostijancic commented on mongodbatlas/resource_mongodbatlas_cloud_provider_snapshot.go
> +			},
documentation can be found in the followup commit.

2021-10-19 21:43 UTC, thetonymaster commented on mongodbatlas/resource_mongodbatlas_cloud_provider_snapshot.go
> +				Required: false,
Add the default `10m` string on the `Default` field

2021-10-20 18:06 UTC, thetonymaster commented on website/docs/r/cloud_provider_snapshot.html.markdown
> +* `timeout`- (Optional) The duration of time to wait to finish the on-demand snapshot. Default is 10m
Can we also add a little explanation as in how the duration is supposed to be written? For Go people this can be self-explanatory but for non-go people this can be hard to understand.

2021-10-20 23:26 UTC, themantissa commented
@ebostijancic thank you for signing the CLA!  Once you respond to @thetonymaster  and have his approval we can move this PR forward.

2021-10-20 23:27 UTC, themantissa approved these changes
LGTM, just needs comments from @thetonymaster  addressed.

2021-10-21 15:47 UTC, thetonymaster approved these changes
LGTM

2021-10-22 15:20 UTC, themantissa commented
@ebostijancic and @thetonymaster fyi the tests are failing with
 --- FAIL: TestProvider (0.01s)
    provider_test.go:44: err: 1 error occurred:
        	* resource mongodbatlas_cloud_provider_snapshot: No Update defined, must set ForceNew on: []string{"timeout"}

2021-10-22 15:46 UTC, coderGo93 requested changes
Looking good but realized some small mistakes like `timeout` is required when it should be optional and lacking the ForceNew

2021-10-22 15:46 UTC, coderGo93 commented on mongodbatlas/resource_mongodbatlas_cloud_provider_snapshot.go
> +				Required: false,
It should be optional, shouldn't it? and it must have `ForceNew: True` since it doesn't have an update.

2021-10-26 19:41 UTC, thetonymaster commented
> @ebostijancic and @thetonymaster fyi the tests are failing with --- FAIL: TestProvider (0.01s) provider_test.go:44: err: 1 error occurred: * resource mongodbatlas_cloud_provider_snapshot: No Update defined, must set ForceNew on: []string{"timeout"}

Yeah the tests didn't ran for some reason until I started the job

2021-10-26 23:56 UTC, themantissa commented
@ebostijancic wanted to check in here and see if you've seen the most recent comments and test failure?

2021-10-27 13:54 UTC, ebostijancic commented on mongodbatlas/resource_mongodbatlas_cloud_provider_snapshot.go
> +				Required: false,
please check latest commit.

2021-10-27 23:54 UTC, themantissa commented
@ebostijancic  once we have a sign off form @coderGo93  we'll merge this.  Thank you!

2021-10-28 15:32 UTC, coderGo93 approved these changes
LGTM, thank you

2021-11-02 20:05 UTC, merged