INTMDB-269: Fix issue with default auto_scaling_disk_gb_enabled value
mongodb/terraform-provider-mongodbatlas pull request #584
Opened 2021-10-13 18:25 UTC by abner-dou

## Description

Please include a summary of the fix/feature/change, including any relevant motivation and context.

Link to any related issue(s):[INTMDB-269](https://jira.mongodb.org/browse/INTMDB-269)

## Type of change:

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Documentation fix/enhancement

## Required Checklist:

- [ ] I have signed the [MongoDB CLA](https://www.mongodb.com/legal/contributor-agreement)
- [ ] I have read the Terraform contribution guidelines
- [ ] I have added tests that prove my fix is effective or that my feature works per HashiCorp requirements
- [ ] I have added any necessary documentation (if appropriate)
- [x] I have run make fmt and formatted my code

## Further comments
TEST RESULT:
-----------------------------------------------------
--- PASS: TestAccResourceMongoDBAtlasCluster_tenant (1558.34s)
PASS
coverage: 6.8% of statements
ok      github.com/mongodb/terraform-provider-mongodbatlas/mongodbatlas 1560.775s       coverage: 6.8% of statements
?       github.com/mongodb/terraform-provider-mongodbatlas/version      [no test files]

2021-10-13 20:33 UTC, thetonymaster requested changes
Talk with @coderGo93 about adding some tests with this, since those tests might need to be added with terratest

2021-10-13 20:53 UTC, thetonymaster commented on mongodbatlas/resource_mongodbatlas_cluster.go
> +		DiskGBEnabled: pointy.Bool(true),
Not really sure about this, thinking how this would be better

2021-10-13 22:10 UTC, abner-dou commented on mongodbatlas/resource_mongodbatlas_cluster.go
> +		DiskGBEnabled: pointy.Bool(true),
I use this way in order to avoid the use of `Default:true` in the `auto_scaling_disk_gb_enabled` but set always to `true` in case that the parameter is not configured
The reason is because is necessary to know when is configured this parameter in the resource definition

2021-10-14 07:52 UTC, andreaangiolillo reviewed
Please, make sure that all the tests are passing before asking for a review. Thanks!
Changes LGTM.

2021-10-20 23:34 UTC, themantissa approved these changes
LGTM

2021-10-21 14:30 UTC, andreaangiolillo approved these changes
LGTM

2021-10-22 18:51 UTC, thetonymaster approved these changes
LGTM, can you just squash the fix commits, since just a fix message is annoying

2021-10-22 19:37 UTC, merged