INTMDB-227:Create new Resource and Datasource for Serverless Instance
mongodb/terraform-provider-mongodbatlas pull request #585
Opened 2021-10-14 00:06 UTC by abner-dou

## Description

Added new resource mongodbatlas_serverless_instance and datasources mongodbatlas_serverless_instances and mongodbatlas_serverless_instances.

New documentation was added

Link to any related issue(s):[INTMDB-227](https://jira.mongodb.org/browse/INTMDB-227)

## Type of change:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [x] Documentation fix/enhancement

## Required Checklist:

- [ ] I have signed the [MongoDB CLA](https://www.mongodb.com/legal/contributor-agreement)
- [ ] I have read the Terraform contribution guidelines
- [ ] I have added tests that prove my fix is effective or that my feature works per HashiCorp requirements
- [x] I have added any necessary documentation (if appropriate)
- [x] I have run make fmt and formatted my code

## Further comments

2021-10-14 00:32 UTC, themantissa commented
@abner-dou not sure what happened here with the tests?

2021-10-14 00:39 UTC, abner-dou commented
@themantissa I cancelled the acctest because I'm running the same test on my other PR, I will resume the acctest for this resume when the other finishes

2021-10-14 08:43 UTC, andreaangiolillo approved these changes
LGTM

2021-10-14 08:43 UTC, andreaangiolillo commented on mongodbatlas/data_source_mongodbatlas_serverless_instances.go
> +	}
[q] I am not sure why these lines are commented out

2021-10-14 08:43 UTC, andreaangiolillo commented on mongodbatlas/data_source_mongodbatlas_serverless_instances.go
> +	}
```suggestion
	projectID, err := d.GetOk("project_id")

	if !(err) {
		return diag.Errorf("project_id must be configured")
	}
```

2021-10-14 14:43 UTC, abner-dou commented on mongodbatlas/data_source_mongodbatlas_serverless_instances.go
> +	}
I forgot to delete it

2021-10-14 14:44 UTC, abner-dou commented on mongodbatlas/data_source_mongodbatlas_serverless_instances.go
> +	}
I was just following the naming convention used in the provider for this cases, but I can change it this way

2021-10-14 19:32 UTC, thetonymaster commented on mongodbatlas/data_source_mongodbatlas_serverless_instances.go
> +	}
I guess `projectIDOK` it's fine since it's a boolean, and not an error

2021-10-14 19:33 UTC, thetonymaster commented on mongodbatlas/data_source_mongodbatlas_serverless_instances.go
> +	}
My only concern here is that variable is only used on that single `if`, don't know if you can actually reduce it to a one liner and assign on true, return error if false

2021-10-14 19:36 UTC, abner-dou commented on mongodbatlas/data_source_mongodbatlas_serverless_instances.go
> +	}
the thing is, I need the other asigned variable `projectID` in order to be use on the rest of the function, if I use a single if line with the declaration, I will need to call again to the `d.GetOk` to obtain the value

2021-10-14 20:15 UTC, thetonymaster commented on mongodbatlas/data_source_mongodbatlas_serverless_instances.go
> +	return serverlessInstancesMap, nil
You can rewrite this as `len(serverlessInstances) > 0` and `return nil, nil`

2021-10-14 20:19 UTC, thetonymaster commented on mongodbatlas/provider.go
> +		resourcesMap["mongodbatlas_serverless_instance"] = resourceMongoDBAtlasServerlessInstance()
can we add a function to add **all** beta features?

2021-10-14 20:20 UTC, thetonymaster commented on mongodbatlas/provider.go
> +		dataSourcesMap["mongodbatlas_serverless_instance"] = dataSourceMongoDBAtlasServerlessInstance()
same here, maybe we can just add a single function to add both, and receives `dataSourcesMap` and `resourcesMap`

2021-10-14 20:27 UTC, thetonymaster commented on mongodbatlas/provider.go
> +		dataSourcesMap["mongodbatlas_serverless_instance"] = dataSourceMongoDBAtlasServerlessInstance()
nvm disregard this comment, just add a variable for` MONGODB_ATLAS_ENABLE_BETA` in the init of the package, set it to true if it's set to true

2021-10-14 20:43 UTC, thetonymaster commented on mongodbatlas/resource_mongodbatlas_serverless_instance.go
> +func resourceMongoDBAtlasServerlessInstanceUpdate(ctx context.Context, data *schema.ResourceData, i interface{}) diag.Diagnostics {
@themantissa will there be a update for this? since we don't have a forcenew on the requiered arguments (or any at all) any chance on this will force on a hard delete (remove then add the resource).

2021-10-14 20:46 UTC, thetonymaster commented on website/docs/d/search_index.html.markdown
> +sidebar_current: "docs-mongodbatlas-datasource-search-index"
is this for another resource?

2021-10-15 22:23 UTC, abner-dou commented on mongodbatlas/data_source_mongodbatlas_serverless_instances.go
> +	return serverlessInstancesMap, nil
this condition is already in line 65 
```
if len(serverlessInstances) == 0 {
		return nil, nil
	}
```

2021-10-15 22:26 UTC, abner-dou commented on website/docs/d/search_index.html.markdown
> +sidebar_current: "docs-mongodbatlas-datasource-search-index"
yes! I realize that I made a previous mistake for this resource in other PR (the change is so little and don't have an impact in provider)

2021-10-20 15:43 UTC, gssbzn commented on mongodbatlas/data_source_mongodbatlas_serverless_instances.go
> +	serverlessInstances, _, err := conn.ServerlessInstances.List(ctx, projectID.(string), options)
[q] why not nil?
```suggestion
	serverlessInstances, _, err := conn.ServerlessInstances.List(ctx, projectID.(string), nil)
```
also are we worry about users with more instances than the default pagination limit?

2021-10-20 20:00 UTC, thetonymaster commented on mongodbatlas/data_source_mongodbatlas_serverless_instances.go
> +	return serverlessInstancesMap, nil
Yes, but there's more flow to this 

````go 

	if len(serverlessInstances) >  0 {

	  var serverlessInstancesMap []map[string]interface{}
          serverlessInstancesMap = make([]map[string]interface{}, len(serverlessInstances))

	for i := range serverlessInstances {
		serverlessInstancesMap[i] = map[string]interface{}{
			"connection_strings_standard_srv": serverlessInstances[i].ConnectionStrings.StandardSrv,
			"create_date":                     serverlessInstances[i].CreateDate,
			"id":                              serverlessInstances[i].ID,
			"links":                           flattenLinks(serverlessInstances[i].Links),
			"mongo_db_version":                serverlessInstances[i].MongoDBVersion,
			"name":                            serverlessInstances[i].Name,
			"provider_settings_backing_provider_name": serverlessInstances[i].ProviderSettings.BackingProviderName,
			"provider_settings_region_name":           serverlessInstances[i].ProviderSettings.RegionName,
			"provider_settings_provider_name":         serverlessInstances[i].ProviderSettings.ProviderName,
			"state_name":                              serverlessInstances[i].StateName,
		}
		return serverlessInstancesMap , nil 
	}
return nil, nil

2021-10-20 20:00 UTC, thetonymaster commented on mongodbatlas/data_source_mongodbatlas_serverless_instances.go
> +	return serverlessInstancesMap, nil
Also why are we returning an error where is none?

2021-10-20 23:39 UTC, themantissa commented on mongodbatlas/resource_mongodbatlas_serverless_instance.go
> +func resourceMongoDBAtlasServerlessInstanceUpdate(ctx context.Context, data *schema.ResourceData, i interface{}) diag.Diagnostics {
Eventually yes, but for now there is not.    This is so tricky in how Terraform handles these!  If someone does not realize what will happen if they, for example, change the name and, due to a ForceNew this removes and recreates the resource, it will delete all that person's data.  If that's the only option that will make sense we need a very very clear warning in the docs that any change of the required parameters will result in a new serverless instance and data loss.  fyi @shum the lack of a clean update on this is really painful for finding a solid way to protect users.

2021-10-21 08:45 UTC, gssbzn commented on mongodbatlas/resource_mongodbatlas_serverless_instance.go
> +func resourceMongoDBAtlasServerlessInstanceUpdate(ctx context.Context, data *schema.ResourceData, i interface{}) diag.Diagnostics {
FWIW names are immutable and will probably remain so

2021-10-25 18:32 UTC, abner-dou commented on mongodbatlas/provider.go
> +		resourcesMap["mongodbatlas_serverless_instance"] = resourceMongoDBAtlasServerlessInstance()
a new function to set only beta features already added

2021-10-26 19:45 UTC, thetonymaster commented on mongodbatlas/resource_mongodbatlas_serverless_instance.go
> +func resourceMongoDBAtlasServerlessInstanceUpdate(ctx context.Context, data *schema.ResourceData, i interface{}) diag.Diagnostics {
So let's leave it like this now, name might have to be `force new` and have a big fat warning in the docs, along other potential arguments. Since now it's in beta don't see an issue leaving it as is until it's implemented. Unless someone complains about the case I mentioned.

2021-10-26 20:25 UTC, abner-dou commented on mongodbatlas/data_source_mongodbatlas_serverless_instances.go
> +	serverlessInstances, _, err := conn.ServerlessInstances.List(ctx, projectID.(string), options)
I already managed the pagination with a recursive function to get all the instances

2021-10-27 00:16 UTC, themantissa requested changes
Docs edits, thanks!

2021-10-27 00:16 UTC, themantissa commented on website/docs/d/search_index.html.markdown
> +sidebar_current: "docs-mongodbatlas-datasource-search-index"
Any change that's not in the scope of the ticket should be another PR.   This is okay this time but work should match the ticket.

2021-10-27 00:16 UTC, themantissa commented on website/docs/r/serverless_instance.html.markdown
> +
We need to document the env var, MONGODB_ATLAS_ENABLE_BETA,  to enable this beta in both the resource and data source pages, the README and the upgrade guide.   You can start it with the following.  Please add any details I've missed:

Serverless instances are in a preview release and do not support some Atlas features at this time.
For a full list of unsupported features, see [Serverless Instance Limitations](https://docs.atlas.mongodb.com/reference/serverless-instance-limitations/).

In order to use this [resource/data source] in Terraform you'll need to set the environment variable MONGODB_ATLAS_ENABLE_BETA to true.

2021-10-27 00:16 UTC, themantissa commented
@abner-dou  is this ready for a re-review from Gustavo?  If so please click the button to re-request.  Though I'd fix the tests first.

2021-10-27 00:17 UTC, themantissa commented on mongodbatlas/resource_mongodbatlas_serverless_instance.go
> +func resourceMongoDBAtlasServerlessInstanceUpdate(ctx context.Context, data *schema.ResourceData, i interface{}) diag.Diagnostics {
👍 fyi @shum

2021-10-27 19:00 UTC, abner-dou commented on website/docs/r/serverless_instance.html.markdown
> +
I already added this note to the datasource/resource doc, to the update-guide and README

2021-10-27 23:32 UTC, themantissa commented on website/docs/r/serverless_instance.html.markdown
> +
Thank you.  I'll add some more around this in the upgrade guide when we are closer to release but this will work for now.

2021-10-27 23:32 UTC, themantissa approved these changes
LGTM, thank you!

2021-10-27 23:33 UTC, themantissa commented
@abner-dou again, is this ready for a re-review from Gustavo? If so please click the button to re-request.   I don't want to do it if it's not ready, i.e. his comments aren't addressed.  @thetonymaster  can you do the DoU review here?

2021-10-28 08:29 UTC, gssbzn approved these changes
LGTM thanks for the pagination

2021-10-28 15:38 UTC, thetonymaster approved these changes
LGTM

2021-10-28 19:47 UTC, merged