INTMDB-260: Added GCP feature for Private Endpoint
mongodb/terraform-provider-mongodbatlas pull request #586
Opened 2021-10-15 22:07 UTC by coderGo93

## Description

- Added GCP feature for Private Endpoint (`mongodbatlas_privatelink_endpoint` and `mongodbatlas_privatelink_endpoint_service`)
- Added example for private endpoint using GCP feature

Not related to ticket:
- Added step to override the plugin with the local plugin generated
- Modified many files in version to use the local plugin instead of downloading the latest version available

Link to any related issue(s):

## Type of change:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update
- [x] Documentation fix/enhancement

## Required Checklist:

- [ ] I have signed the [MongoDB CLA](https://www.mongodb.com/legal/contributor-agreement)
- [ ] I have read the Terraform contribution guidelines
- [ ] I have added tests that prove my fix is effective or that my feature works per HashiCorp requirements
- [x] I have added any necessary documentation (if appropriate)
- [x] I have run make fmt and formatted my code

## Further comments

2021-10-21 16:59 UTC, andreaangiolillo approved these changes
LGTM

2021-10-21 16:59 UTC, andreaangiolillo commented on mongodbatlas/data_source_mongodbatlas_privatelink_endpoint.go
> +			},
[q] Is there any reason why we are not adding the ID? https://docs.atlas.mongodb.com/reference/api/private-endpoints-service-get-one/
![Screenshot 2021-10-21 at 17 51 04](https://user-images.githubusercontent.com/5663078/138322326-559562fe-d121-47a0-93ba-b63600b6874a.png)

2021-10-21 16:59 UTC, andreaangiolillo commented on mongodbatlas/data_source_mongodbatlas_privatelink_endpoint_service.go
> +			"endpoints": {
I see that the ID is not here neither. Probably there is a reason, I am just wondering why

2021-10-21 16:59 UTC, andreaangiolillo commented on mongodbatlas/resource_mongodbatlas_privatelink_endpoint_service.go
> +	}
```suggestion
	for _, tfMapRaw := range tfList {
		if tfMap, ok := tfMapRaw.(map[string]interface{}) ok {
			apiObject := expandGCPEndpoint(tfMap)

			if apiObject == nil {
				continue
			}

			apiObjects = append(apiObjects, apiObject)
		}
	}
```

2021-10-21 23:49 UTC, coderGo93 commented on mongodbatlas/data_source_mongodbatlas_privatelink_endpoint_service.go
> +			"endpoints": {
The parameter only appears if you used the GCP provider and in docs doesn't show the `id` neither in api response in the `endpoints` parameter

2021-10-21 23:51 UTC, coderGo93 commented on mongodbatlas/data_source_mongodbatlas_privatelink_endpoint.go
> +			},
Technically, it does, is stored in encoded state with the parameter `private_link_id` which is the ID for AWS, AZURE and GCP.

2021-10-26 19:23 UTC, thetonymaster commented on mongodbatlas/resource_mongodbatlas_privatelink_endpoint_service.go
> +	if providerName == "AWS" {
Use a `switch` instead of consecutive `if`

2021-10-26 19:36 UTC, coderGo93 commented on mongodbatlas/resource_mongodbatlas_privatelink_endpoint_service.go
> +	}
Done

2021-10-26 19:40 UTC, thetonymaster commented on mongodbatlas/resource_mongodbatlas_privatelink_endpoint_service.go
> +	if gPIOk {
Don't know if we can move the specific data for each of the providers to a function for each one of them, it is a lot of stuff floating around

2021-10-26 22:01 UTC, coderGo93 commented on mongodbatlas/resource_mongodbatlas_privatelink_endpoint_service.go
> +	if providerName == "AWS" {
Done, thank you

2021-10-26 22:01 UTC, coderGo93 commented on mongodbatlas/resource_mongodbatlas_privatelink_endpoint_service.go
> +	if gPIOk {
Moved to inside of switch

2021-10-26 23:54 UTC, themantissa requested changes
Mostly small docs edits. Thanks!

2021-10-26 23:54 UTC, themantissa commented on examples/gcp-atlas-privatelink/Readme.md
> +3. Once authenticated, it will appear an input to choose the project:
This seems to be missing steps?

2021-10-26 23:54 UTC, themantissa commented on examples/gcp-atlas-privatelink/Readme.md
> +This project aims to provide an example of using GCP and MongoDB Atlas together.
This is sorta true but really this is "providing an example of setting up GCP Private Service Connect with MongoDB Atlas."

2021-10-26 23:54 UTC, themantissa commented on examples/gcp-atlas-privatelink/Readme.md
> +* Terraform v0.13
.13+ ?

2021-10-26 23:54 UTC, themantissa commented on examples/gcp-atlas-privatelink/Readme.md
> +- GCP-MongoDB Private Link
Technically GCP's version of PrivateLink is Private Service Connect (PSC) so even though our resource is called private link we should use their term when Google specific.

2021-10-26 23:54 UTC, themantissa commented on examples/gcp-atlas-privatelink/main.tf
> +# Create a Google 50 Addresses
Slight edit:
Create 50 Google Addresses

2021-10-26 23:54 UTC, themantissa commented on examples/gcp-atlas-privatelink/main.tf
> +# Creates a 50 Forwarding rules
Slight edit:
Create 50 forwarding rules

2021-10-26 23:54 UTC, themantissa commented on website/docs/r/privatelink_endpoint.html.markdown
>    AWS:
The links above (line 37) are more updated so let's remove lines 39-125 as they are often behind.

2021-10-26 23:54 UTC, themantissa commented on website/docs/r/privatelink_endpoint.html.markdown
> +* `endpoint_group_names` - GCP network endpoint groups corresponding to the Private Service Connect endpoint service.
Can we put a header like was done for Status for the parameters that apply to a single cloud provider?  Will make it easier to read.  e.g. 
AWS:
 *parameters
GCP

2021-10-26 23:54 UTC, themantissa commented on website/docs/r/privatelink_endpoint_service.html.markdown
> +# Create a Google 50 Addresses
Slight edit (same as in the example) - note for any of these comments only proper nouns should be capitalized: 
Create 50 Google addresses

2021-10-26 23:54 UTC, themantissa commented on website/docs/r/privatelink_endpoint_service.html.markdown
> +# Creates a 50 Forwarding rules
Slight edit:
Create 50 forwarding rules

2021-10-27 10:38 UTC, SMR39 commented
excited for this to get merged we are blocked with vpc peering limitations with GCP shared VPC architecture

2021-10-27 23:36 UTC, themantissa reviewed
One of the steps I commented on in the example seems to still be missing steps.  Please either fix or explain why it seems to just drop off there.

2021-10-27 23:36 UTC, themantissa commented on examples/gcp-atlas-privatelink/Readme.md
> +3. Once authenticated, it will appear an input to choose the project:
@coderGo93 still missing something here? Step 3 reads like there should be more steps?

2021-10-28 00:07 UTC, themantissa requested changes
Got the context now, thank you.  Just adding a small edit to make clearer and this is done.

2021-10-28 00:07 UTC, themantissa commented on examples/gcp-atlas-privatelink/Readme.md
> +3. Once authenticated, it will appear an input to choose the project. After is chosen it will appear a message about SDK is configured:
Okay I think we are much closer.  I see it's an intro to what's below.  Let's edit steps 1-3  a bit:
1. Install the GCloud SDK by following the steps from the [official GCP documentation](https://cloud.google.com/sdk/docs/install).
2. Run the command `gcloud init` and authenticate with GCP.
3. Once authenticated you will need to select a project to use.   After you select a project a success message will appear, see the example below.  You are then ready to proceed.

2021-10-28 15:29 UTC, coderGo93 commented on examples/gcp-atlas-privatelink/Readme.md
> +3. Once authenticated, it will appear an input to choose the project. After is chosen it will appear a message about SDK is configured:
Updated, thank you melissa

2021-10-28 19:55 UTC, themantissa approved these changes
Thank you! LGTM.  Needs a DoU review.

2021-10-29 15:45 UTC, thetonymaster approved these changes
LGTM

2021-10-29 22:16 UTC, merged