INTMDB-222: Added Synonyms to Search Index RS and DS
mongodb/terraform-provider-mongodbatlas pull request #591
Opened 2021-10-25 17:49 UTC by abner-dou

## Description

Added synonyms support to search index resource and datasource

Link to any related issue(s):[INTMDB-222](https://jira.mongodb.org/browse/INTMDB-222)

## Type of change:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [x] Documentation fix/enhancement

## Required Checklist:

- [ ] I have signed the [MongoDB CLA](https://www.mongodb.com/legal/contributor-agreement)
- [ ] I have read the Terraform contribution guidelines
- [x] I have added tests that prove my fix is effective or that my feature works per HashiCorp requirements
- [x] I have added any necessary documentation (if appropriate)
- [x] I have run make fmt and formatted my code

## Further comments

2021-10-26 10:36 UTC, andreaangiolillo approved these changes
LGTM

2021-10-26 10:36 UTC, andreaangiolillo commented on mongodbatlas/resource_mongodbatlas_search_index.go
> +}
```suggestion
func expandSearchIndexSynonyms(d *schema.ResourceData) []map[string]interface{} {
	var synonymsList []map[string]interface{}

	synonymsDoc := map[string]interface{}{}

	if vSynonyms, vSynonymsOK := d.GetOk("synonyms"); vSynonymsOK{
		for _, s := range vSynonyms.(*schema.Set).List() {
			synonym := s.(map[string]interface{})

			synonymsDoc["name"] = synonym["name"]
			synonymsDoc["analyzer"] = synonym["analyzer"]
			synonymsDoc["source"] = map[string]interface{}{
				"collection": synonym["source_collection"],
			}
			synonymsList = append(synonymsList, synonymsDoc)
		}
	}
	
	return synonymsList
}
```

2021-10-26 17:44 UTC, thetonymaster approved these changes
LGTM just check @andreaangiolillo's comment

2021-10-26 20:24 UTC, abner-dou commented on mongodbatlas/resource_mongodbatlas_search_index.go
> +}
already changed :D

2021-10-27 00:05 UTC, themantissa approved these changes
LGTM but just pinged the search team to make sure okay with them.  Standby for their input.

2021-10-27 00:44 UTC, navenoxin requested changes
Am I reading this correctly in that we are changing the syntax slightly here? Can we use the original syntax where a synonym mapping looks like

```json5
{
  name: "synonym mapping name",
  source: {
    collection: "source collection"
  },
  analyzer: "some analyzer"
}
```

instead of

```json5
{
  name: "synonym mapping name",
  source_collection: "source collection",
  analyzer: "some analyzer"
}
```

We do not want to change the index definition syntax from what is presented elsewhere and [explained in the docs](https://docs.atlas.mongodb.com/reference/atlas-search/synonyms/#syntax).

2021-10-27 15:59 UTC, abner-dou commented
@navenoxin In response for your latest comment:

Are you planning to add more properties to the `source` document or just the `collection` properties, because adding sub-levels to the properties adds more complexity to the resource in terraform provider.

2021-10-27 16:11 UTC, navenoxin commented
@abner-dou We do not plan on adding more properties to the source document in the immediate future. Understood re: this adding a little complexity to the terraform provider, but I'd argue it is more important to present a uniform syntax everywhere this is exposed.

CC @themantissa @doug-ol

2021-10-28 22:55 UTC, navenoxin requested changes
A few corrections, otherwise no blocking objections

2021-10-28 22:55 UTC, navenoxin commented on website/docs/d/search_index.html.markdown
> +* `database` - Name of the database the collection is in.
why remove `(Required)` here?

2021-10-28 22:55 UTC, navenoxin commented on website/docs/d/search_index.html.markdown
> +* `synonyms.#.analyzer` - Name of the [analyzer](https://docs.atlas.mongodb.com/reference/atlas-search/analyzers/#std-label-analyzers-ref) to use with this synonym mapping. If `mappings.dynamic` is `
please remove this, it is not true.

```suggestion
* `synonyms.#.analyzer` - Name of the [analyzer](https://docs.atlas.mongodb.com/reference/atlas-search/analyzers/#std-label-analyzers-ref) to use with this synonym mapping.
```

2021-10-28 22:55 UTC, navenoxin commented on website/docs/d/search_indexes.html.markdown
> +* `synonyms.#.analyzer` - Name of the [analyzer](https://docs.atlas.mongodb.com/reference/atlas-search/analyzers/#std-label-analyzers-ref) to use with this synonym mapping. If `mappings.dynamic` is `
please remove this, it is not true.

```suggestion
* `synonyms.#.analyzer` - Name of the [analyzer](https://docs.atlas.mongodb.com/reference/atlas-search/analyzers/#std-label-analyzers-ref) to use with this synonym mapping.
```

2021-10-28 22:55 UTC, navenoxin commented on website/docs/r/search_index.html.markdown
> +* `analyzer` - (Required) Name of the [analyzer](https://docs.atlas.mongodb.com/reference/atlas-search/analyzers/#std-label-analyzers-ref) to use with this synonym mapping. If you set `mappings.dynam
changed note re: dynamic indexes, clarified scope of where custom analyzer components are invalid

```suggestion
* `analyzer` - (Required) Name of the [analyzer](https://docs.atlas.mongodb.com/reference/atlas-search/analyzers/#std-label-analyzers-ref) to use with this synonym mapping. Atlas Search doesn't support these [custom analyzer](https://docs.atlas.mongodb.com/reference/atlas-search/analyzers/custom/#std-label-custom-analyzers) tokenizers and token filters in [analyzers used in synonym mappings](https://docs.atlas.mongodb.com/reference/atlas-search/synonyms/#options):
```

2021-11-01 16:05 UTC, navenoxin requested changes
@abner-dou please address suggestions from my last review

2021-11-01 16:32 UTC, navenoxin approved these changes

2021-11-01 16:32 UTC, merged