INTMDB-276: Added VersionReleaseSystem parameter for resource/datasource(s) of cluster
mongodb/terraform-provider-mongodbatlas pull request #623
Opened 2021-11-23 23:26 UTC by coderGo93

## Description

- Added field `version_release_system` for resource and datasource(s) of cluster
- Updated docs

NOTE: Still waiting for [PR](https://github.com/mongodb/go-client-mongodb-atlas/pull/270) to be merged first then updated the vendor, so it can pass the checks.

Link to any related issue(s):

## Type of change:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [x] Documentation fix/enhancement

## Required Checklist:

- [ ] I have signed the [MongoDB CLA](https://www.mongodb.com/legal/contributor-agreement)
- [ ] I have read the Terraform contribution guidelines
- [x] I have added tests that prove my fix is effective or that my feature works per HashiCorp requirements
- [x] I have added any necessary documentation (if appropriate)
- [x] I have run make fmt and formatted my code

## Further comments

2021-11-30 18:34 UTC, thetonymaster approved these changes
LGTM

2021-12-02 01:10 UTC, themantissa requested changes
See suggested changes in docs.  Also this should be added to advanced_clusters as well.   Please add both to this PR.

2021-12-02 01:10 UTC, themantissa commented on website/docs/r/cluster.html.markdown
> +* `version_release_system` - (Optional) - Method by which this cluster maintains the MongoDB versions. Valid values are `CONTINUOUS` or `LTS` (Long Term Support). This parameter defaults to `LTS`. If
```suggestion
* `version_release_system` - (Optional) - Release cadence that Atlas uses for this cluster. This parameter defaults to `LTS`. If you set this field to `CONTINUOUS`, you must omit the `mongo_db_major_version` field. Atlas accepts:
   - `CONTINUOUS`:  Atlas creates your cluster using the most recent MongoDB release. Atlas automatically updates your cluster to the latest major and rapid MongoDB releases as they become available.
   - `LTS`: Atlas creates your cluster using the latest patch release of the MongoDB version that you specify in the mongoDBMajorVersion field. Atlas automatically updates your cluster to subsequent patch releases of this MongoDB version. Atlas doesn't update your cluster to newer rapid or major MongoDB releases as they become available.
```

2021-12-02 01:10 UTC, themantissa commented on website/docs/d/clusters.html.markdown
> +* `version_release_system` - Method by which this cluster maintains the MongoDB versions.
```suggestion
* `version_release_system` - Release cadence that Atlas uses for this cluster.
```

2021-12-02 01:10 UTC, themantissa commented on website/docs/d/cluster.html.markdown
> +* `version_release_system` - Method by which this cluster maintains the MongoDB versions.
```suggestion
* `version_release_system` - Release cadence that Atlas uses for this cluster.
```

2021-12-03 00:57 UTC, themantissa approved these changes
LGTM!

2021-12-09 17:35 UTC, gssbzn commented on go.sum
> +go.mongodb.org/atlas v0.14.1-0.20211130093552-cb00594ec51e h1:kYgaXVVngAzJFFXYrwL1x+73Y7zrJ37KQw/1huAOWJY=
[q] `go mod tidy`?

2021-12-09 17:35 UTC, gssbzn approved these changes
LGTM

2021-12-09 17:45 UTC, coderGo93 commented on go.sum
> +go.mongodb.org/atlas v0.14.1-0.20211130093552-cb00594ec51e h1:kYgaXVVngAzJFFXYrwL1x+73Y7zrJ37KQw/1huAOWJY=
Done, thank you

2021-12-15 08:56 UTC, andreaangiolillo approved these changes
LGTM

2021-12-18 03:50 UTC, merged