INTMDB-284: Updated docs in alert configuration resource and datasource
mongodb/terraform-provider-mongodbatlas pull request #645
Opened 2021-12-21 22:41 UTC by coderGo93

## Description

- Updated docs of resource and datasource of alert configuration

Link to any related issue(s):
#632
## Type of change:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [x] Documentation fix/enhancement

## Required Checklist:

- [ ] I have signed the [MongoDB CLA](https://www.mongodb.com/legal/contributor-agreement)
- [ ] I have read the Terraform contribution guidelines
- [ ] I have added tests that prove my fix is effective or that my feature works per HashiCorp requirements
- [ ] I have added any necessary documentation (if appropriate)
- [ ] I have run make fmt and formatted my code

## Further comments

2021-12-22 00:19 UTC, themantissa requested changes
A few edits for clarity

2021-12-22 00:19 UTC, themantissa commented on website/docs/r/alert_configuration.html.markdown
> +* `email_enabled` - Flag indicating email notifications must be sent. Set this value if you set `type_name` to `ORG`, `GROUP`, or `USER`.
Should is correct here and is what is in the original documenation.  
```suggestion
* `email_enabled` - Flag indicating email notifications should be sent. This flag is only valid if `type_name` is set to `ORG`, `GROUP`, or `USER`.
```

2021-12-22 00:19 UTC, themantissa commented on website/docs/r/alert_configuration.html.markdown
> +* `sms_enabled` - Flag indicating if text message notifications should be sent to this user's mobile phone. Set this value if you set `type_name` to `ORG`, `GROUP`, or `USER`.
```suggestion
* `sms_enabled` - Flag indicating if text message notifications should be sent to this user's mobile phone. This flag is only valid if `type_name` is set to `ORG`, `GROUP`, or `USER`. 
```

2021-12-22 00:19 UTC, themantissa commented on website/docs/d/alert_configuration.html.markdown
> +* `email_enabled` - Flag indicating email notifications must be sent. Atlas returns this value if you set `type_name` to `ORG`, `GROUP`, or `USER`.
```suggestion
* `email_enabled` - Flag indicating email notifications should be sent. Atlas returns this value if `type_name` is set  to `ORG`, `GROUP`, or `USER`.
```

2021-12-22 00:19 UTC, themantissa commented on website/docs/d/alert_configuration.html.markdown
> +* `sms_enabled` - Flag indicating text notifications must be sent. Atlas returns this value if you set `type_name` to `ORG`, `GROUP`, or `USER`.
```suggestion
* `sms_enabled` - Flag indicating text notifications should be sent. Atlas returns this value if `type_name` is set to `ORG`, `GROUP`, or `USER`.
```

2021-12-22 00:19 UTC, themantissa commented on website/docs/r/alert_configuration.html.markdown
> +* `roles` - Optional. If you include this field, Atlas sends alerts only to users assigned the roles you specify in the array. If you omit this field, Atlas sends alerts to users assigned any role. S
```suggestion
* `roles` - Optional. One or more roles that receive the configured alert. If you include this field, Atlas sends alerts only to users assigned the roles you specify in the array. If you omit this field, Atlas sends alerts to users assigned any role. This parameter is only valid if `type_name` is set to `ORG`, `GROUP`, or `USER`. 
```

2022-01-06 00:43 UTC, themantissa approved these changes
LGTM!

2022-01-07 17:05 UTC, thetonymaster approved these changes
LGTM

2022-01-07 17:51 UTC, andreaangiolillo approved these changes

2022-01-10 17:15 UTC, merged