INTMDB-15: Added parameter advanced conf for cluster datasource
mongodb/terraform-provider-mongodbatlas pull request #646
Opened 2021-12-23 00:59 UTC by coderGo93

## Description

- Added parameter `advanced_configuration` in datasource(s) of cluster and its docs
- Added tests in datasource of cluster called `TestAccDataSourceMongoDBAtlasCluster_advancedConf` and `TestAccDataSourceMongoDBAtlasClusters_advancedConf`

Link to any related issue(s):

## Type of change:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update
- [x] Documentation fix/enhancement

## Required Checklist:

- [ ] I have signed the [MongoDB CLA](https://www.mongodb.com/legal/contributor-agreement)
- [ ] I have read the Terraform contribution guidelines
- [x] I have added tests that prove my fix is effective or that my feature works per HashiCorp requirements
- [x] I have added any necessary documentation (if appropriate)
- [x] I have run make fmt and formatted my code

## Further comments

2022-01-06 00:52 UTC, themantissa requested changes
Just a small edit to remove an extra character.  Otherwise good.

2022-01-06 00:52 UTC, themantissa commented on website/docs/d/cluster.html.markdown
> +* `default_read_concern` - [Default level of acknowledgment requested from MongoDB for read operations](https://docs.mongodb.com/manual/reference/read-concern/) set for this cluster. M;ongoDB 4.4 clu
```suggestion
* `default_read_concern` - [Default level of acknowledgment requested from MongoDB for read operations](https://docs.mongodb.com/manual/reference/read-concern/) set for this cluster. M;ongoDB 4.4 clusters default to [available](https://docs.mongodb.com/manual/reference/read-concern-available/).
```
```suggestion
* `default_read_concern` - [Default level of acknowledgment requested from MongoDB for read operations](https://docs.mongodb.com/manual/reference/read-concern/) set for this cluster. MongoDB 4.4 clusters default to [available](https://docs.mongodb.com/manual/reference/read-concern-available/).
```

2022-01-06 00:52 UTC, themantissa commented on website/docs/d/clusters.html.markdown
> +* `default_read_concern` - [Default level of acknowledgment requested from MongoDB for read operations](https://docs.mongodb.com/manual/reference/read-concern/) set for this cluster. M;ongoDB 4.4 clu
```suggestion
* `default_read_concern` - [Default level of acknowledgment requested from MongoDB for read operations](https://docs.mongodb.com/manual/reference/read-concern/) set for this cluster. M;ongoDB 4.4 clusters default to [available](https://docs.mongodb.com/manual/reference/read-concern-available/).
```
```suggestion
* `default_read_concern` - [Default level of acknowledgment requested from MongoDB for read operations](https://docs.mongodb.com/manual/reference/read-concern/) set for this cluster. MongoDB 4.4 clusters default to [available](https://docs.mongodb.com/manual/reference/read-concern-available/).
```

2022-01-06 20:16 UTC, themantissa approved these changes
LGTM!

2022-01-07 17:15 UTC, thetonymaster approved these changes
LGTM

2022-01-07 17:46 UTC, andreaangiolillo approved these changes
LGTM

2022-01-12 13:01 UTC, merged