INTMDB-319: Add support for parameter unordered in resource_mongodbatlas_event_trigger
mongodb/terraform-provider-mongodbatlas pull request #739
Opened 2022-05-27 14:44 UTC by martinstibbe

## Description

Add support for parameter unordered in resource_mongodbatlas_event_trigger

Link to any related issue(s):
https://jira.mongodb.org/browse/INTMDB-319
## Type of change:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Documentation fix/enhancement

## Required Checklist:

- [ ] I have signed the [MongoDB CLA](https://www.mongodb.com/legal/contributor-agreement)
- [ ] I have read the Terraform contribution guidelines
- [ ] I have added tests that prove my fix is effective or that my feature works per HashiCorp requirements
- [ ] I have added any necessary documentation (if appropriate)
- [ ] I have run make fmt and formatted my code

## Further comments

2022-05-27 15:22 UTC, themantissa requested changes
Just a few docs changes, mostly since I didn't get you this in slack sooner :)

2022-05-27 15:22 UTC, themantissa commented on website/docs/d/event_trigger.html.markdown
> +* `unordered` - Sort order for `DATABASE` type.
Sorry I didn't get to you on this but the docs have a better explanation: from https://www.mongodb.com/docs/atlas/app-services/admin/api/v3/#operation/adminCreateTrigger   
```suggestion
* `unordered` - Only Available for Database Triggers. If true, event ordering is disabled and this trigger can process events in parallel. If false, event ordering is enabled and the trigger executes serially.
```

2022-05-27 15:22 UTC, themantissa commented on website/docs/d/event_triggers.html.markdown
> +* `unordered` - Sort order for `DATABASE` type.
```suggestion
* `unordered` - Only Available for Database Triggers. If true, event ordering is disabled and this trigger can process events in parallel. If false, event ordering is enabled and the trigger executes serially.
```

2022-05-27 15:22 UTC, themantissa commented on website/docs/r/event_trigger.html.markdown
> +* `unordered` - (Optional) Optional for `DATABASE` type.
```suggestion
* `unordered` - (Optional) Optional for for Database Triggers. If true, event ordering is disabled and this trigger can process events in parallel. If false, event ordering is enabled and the trigger executes serially.
```

2022-05-27 15:26 UTC, martinstibbe commented on website/docs/r/event_trigger.html.markdown
> +* `unordered` - (Optional) Optional for `DATABASE` type.
Updated

2022-05-27 15:26 UTC, martinstibbe commented on website/docs/d/event_triggers.html.markdown
> +* `unordered` - Sort order for `DATABASE` type.
Updated

2022-05-30 14:26 UTC, andreaangiolillo approved these changes
Just one comment.

2022-05-30 14:26 UTC, andreaangiolillo commented on mongodbatlas/data_source_mongodbatlas_event_triggers.go
> +				"unordered":                   eventTriggers[i].Config.Unordered,
[q] Could you update the tests to use `unordered`?

2022-05-31 14:37 UTC, martinstibbe commented on mongodbatlas/data_source_mongodbatlas_event_triggers.go
> +				"unordered":                   eventTriggers[i].Config.Unordered,
Added

2022-06-01 15:45 UTC, martinstibbe commented on website/docs/d/event_trigger.html.markdown
> +* `unordered` - Sort order for `DATABASE` type.
Added new text description

2022-06-01 15:46 UTC, andreaangiolillo approved these changes

2022-06-02 18:57 UTC, themantissa approved these changes
Thank you for the fixes, LGTM!

2022-06-02 18:58 UTC, merged