INTDB-301-DOC: Move Federated Docs to separate branch
mongodb/terraform-provider-mongodbatlas pull request #747
Opened 2022-06-04 00:21 UTC by martinstibbe

## Description

Documentation for Federated Settings Datasources resources 

Link to any related issue(s):

https://jira.mongodb.org/browse/INTMDB-301

## Type of change:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Documentation fix/enhancement

## Required Checklist:

- [ ] I have signed the [MongoDB CLA](https://www.mongodb.com/legal/contributor-agreement)
- [ ] I have read the Terraform contribution guidelines
- [ ] I have added tests that prove my fix is effective or that my feature works per HashiCorp requirements
- [ ] I have added any necessary documentation (if appropriate)
- [ ] I have run make fmt and formatted my code

## Further comments

2022-06-28 00:03 UTC, themantissa requested changes
I honestly ran out of steam at the end and just started commenting vs suggested changes.  The docs are so important to users being able to use these resources and data sources.  Please try to give this some attention.

2022-06-28 00:03 UTC, themantissa commented on website/docs/d/federated_settings.html.markdown
> +* `id` - nique 24-hexadecimal digit string that identifies this federation.
```suggestion
* `id` - Unique 24-hexadecimal digit string that identifies this federation.
```

2022-06-28 00:03 UTC, themantissa commented on website/docs/d/federated_settings.html.markdown
> +page_title: "MongoDB Atlas: mongodbatlas_cloud_federated_settings"
All of these are just mongodbatlas_
```suggestion
page_title: "MongoDB Atlas: mongodbatlas_federated_settings"
```

2022-06-28 00:03 UTC, themantissa commented on website/docs/d/federated_settings.html.markdown
> +`mongodbatlas_cloud_federated_settings` provides an Federated Settings datasource. Atlas Cloud Federated Settings provides federated settings outputs.
```suggestion
`mongodbatlas_federated_settings` provides a federated settings data source. Atlas federated settings provides federated settings outputs.
```

2022-06-28 00:03 UTC, themantissa commented on website/docs/d/federated_settings.html.markdown
> +    Provides an Federated Settings datasource.
```suggestion
    Provides a federated settings data source.
```

2022-06-28 00:03 UTC, themantissa commented on website/docs/d/federated_settings_identity_provider.html.markdown
> +page_title: "MongoDB Atlas: mongodbatlas_cloud_federated_settings_identity_provider"
```suggestion
page_title: "MongoDB Atlas: mongodbatlas_federated_settings_identity_provider"
```

2022-06-28 00:03 UTC, themantissa commented on website/docs/d/federated_settings_identity_provider.html.markdown
> +    Provides an Federated Settings Organization Identity Provider Datasource.
```suggestion
    Provides a federated settings organization identity provider data source.
```

2022-06-28 00:03 UTC, themantissa commented on website/docs/d/federated_settings.html.markdown
> +data "mongodbatlas_cloud_federated_settings" "settings" {
```suggestion
data "mongodbatlas_federated_settings" "settings" {
```

2022-06-28 00:03 UTC, themantissa commented on website/docs/d/federated_settings.html.markdown
> +# mongodbatlas_cloud_federated_settings
```suggestion
# mongodbatlas_federated_settings
```

2022-06-28 00:03 UTC, themantissa commented on website/docs/d/federated_settings_identity_provider.html.markdown
> +# mongodbatlas_cloud_federated_settings_identity_provider
```suggestion
# mongodbatlas_federated_settings_identity_provider
```

2022-06-28 00:03 UTC, themantissa commented on website/docs/d/federated_settings_identity_provider.html.markdown
> +`mongodbatlas_cloud_federated_settings_identity_provider` provides an Federated Settings Identity Provider datasource. Atlas Cloud Federated Settings Identity Provider provides federated settings out
```suggestion
`mongodbatlas_federated_settings_identity_provider` provides a federated settings identity provider data source. Atlas federated settings identity provider provides federated settings outputs for the configured identity provider.
```

2022-06-28 00:03 UTC, themantissa commented on website/docs/d/federated_settings_identity_provider.html.markdown
> +resource "mongodbatlas_cloud_federated_settings_identity_provider" "identity_provider" {
```suggestion
resource "mongodbatlas_federated_settings_identity_provider" "identity_provider" {
```

2022-06-28 00:03 UTC, themantissa commented on website/docs/d/federated_settings_identity_provider.html.markdown
> +  federation_settings_id     = "627a9687f7f7f7f774de306f14"
Just double checking that all actual values in examples are fake, correct?

2022-06-28 00:03 UTC, themantissa commented on website/docs/d/federated_settings_identity_provider.html.markdown
> +resource "mongodbatlas_cloud_federated_settings_identity_provider" "identity_provider" {
Looking at your example in [examples/Federated-Settings/main.tf](https://github.com/mongodb/terraform-provider-mongodbatlas/pull/742/files#diff-97e59f55c8af0e7bf39101dd03c05da51f79b9f888d8f2fbd45f2e256174b0f6) this does not have all the same variables.  I'm not sure if the diff is required or not (the docs sadly don't seem to have) but if so these should match up.

2022-06-28 00:03 UTC, themantissa commented on website/docs/d/federated_settings_identity_provider.html.markdown
> +* `identity_provider_id` - (Required) Unique 24-hexadecimal digit string that identifies the federated authentication configuration.
```suggestion
* `identity_provider_id` - (Required) Unique 20-hexadecimal digit string that identifies the IdP.
```

2022-06-28 00:03 UTC, themantissa commented on website/docs/d/federated_settings_identity_provider.html.markdown
> +* `associated_orgs` - List that contains the configured domains from which users can log in for this IdP.
```suggestion
* `associated_orgs` - List that contains the organizations from which users can log in for this IdP.
```

2022-06-28 00:03 UTC, themantissa commented on website/docs/d/federated_settings_identity_providers.html.markdown
> +---
Same comments here as above in singular datasource

2022-06-28 00:03 UTC, themantissa commented on website/docs/d/federated_settings_org_config.html.markdown
> +page_title: "MongoDB Atlas: mongodbatlas_cloud_federated_settings_org_config"
```suggestion
page_title: "MongoDB Atlas: mongodbatlas_federated_settings_org_config"
```

2022-06-28 00:03 UTC, themantissa commented on website/docs/d/federated_settings_org_config.html.markdown
> +    Provides an Federated Settings Organization Configuration.
```suggestion
    Provides a federated settings organization configuration.
```

2022-06-28 00:03 UTC, themantissa commented on website/docs/d/federated_settings_org_config.html.markdown
> +# mongodbatlas_cloud_federated_settings_org_configs
```suggestion
# mongodbatlas_federated_settings_org_configs
```

2022-06-28 00:03 UTC, themantissa commented on website/docs/d/federated_settings_org_config.html.markdown
> +`mongodbatlas_cloud_federated_settings_org_config` provides an Federated Settings Identity Providers datasource. Atlas Cloud Federated Settings Organizational configuration provides federated setting
```suggestion
`mongodbatlas_federated_settings_org_config` provides a federated settings identity providers data source. Atlas federated settings organizational configuration provides federated settings outputs for the configured organizational configuration.
```

2022-06-28 00:03 UTC, themantissa commented on website/docs/d/federated_settings_org_config.html.markdown
> +resource "mongodbatlas_cloud_federated_settings_org_config" "org_connections" {
```suggestion
resource "mongodbatlas_federated_settings_org_config" "org_connections" {
```

2022-06-28 00:03 UTC, themantissa commented on website/docs/d/federated_settings_org_config.html.markdown
> +* `domain_allow_list` - List that contains the approved domains from which organization users can log in.
Please be sure to capture all relevant doc, e.g.: 
```suggestion
* `domain_allow_list` - List that contains the approved domains from which organization users can log in.  Note: If the organization uses an identity provider,  `domain_allow_list` includes: any SSO domains associated with organization's identity provider and any custom domains associated with the specific organization.
```

2022-06-28 00:03 UTC, themantissa commented on website/docs/d/federated_settings_org_config.html.markdown
> +* `domain_restriction_enabled` - Flag that indicates whether domain restriction is enabled for the connected organization.
```suggestion
* `domain_restriction_enabled` - Flag that indicates whether domain restriction is enabled for the connected organization.  User Conflicts returns null when `domain_restriction_enabled` is false.
```

2022-06-28 00:03 UTC, themantissa commented on website/docs/d/federated_settings_org_config.html.markdown
> +* `identity_provider_id` - Unique 24-hexadecimal digit string that identifies the federated authentication configuration.
```suggestion
* `identity_provider_id` - Unique 20-hexadecimal digit string that identifies the identity provider associated with the connected organization.
```

2022-06-28 00:03 UTC, themantissa commented on website/docs/d/federated_settings_org_config.html.markdown
> +* `post_auth_role_grants` - List that contains the default roles granted to users who authenticate through the IdP in a connected organization. If you provide a postAuthRoleGrants field in the reques
```suggestion
* `post_auth_role_grants` - List that contains the default [roles](https://www.mongodb.com/docs/atlas/reference/user-roles/#std-label-organization-roles) granted to users who authenticate through the IdP in a connected organization. If you provide a postAuthRoleGrants field in the request, the array that you provide replaces the current postAuthRoleGrants.
```

2022-06-28 00:03 UTC, themantissa commented on website/docs/d/federated_settings_org_config.html.markdown
> +  ### Role_mappings
```suggestion
 ### Role_mappings
```

2022-06-28 00:03 UTC, themantissa commented on website/docs/d/federated_settings_org_config.html.markdown
> +### User Conflicts
Should this not have a variable name?  This has a space?  I put the same above but we'll need to fix both.

2022-06-28 00:03 UTC, themantissa commented on website/docs/d/federated_settings_org_config.html.markdown
> +* `role` - Specifies the Role that is attached to the Role Mapping.
wouldn't this still output the orgId for the entry?

2022-06-28 00:03 UTC, themantissa commented on website/docs/d/federated_settings_org_configs.html.markdown
> +---
Same as singular page above

2022-06-28 00:03 UTC, themantissa commented on website/docs/d/federated_settings_org_role_mapping.html.markdown
> +page_title: "MongoDB Atlas: mongodbatlas_cloud_federated-settings_role_mapping"
```suggestion
page_title: "MongoDB Atlas: mongodbatlas_federated-settings_role_mapping"
```

2022-06-28 00:03 UTC, themantissa commented on website/docs/d/federated_settings_org_role_mapping.html.markdown
> +    Provides an Federated settings Role Mapping Datasource.
```suggestion
    Provides a federated settings role mapping data source.
```

2022-06-28 00:03 UTC, themantissa commented on website/docs/d/federated_settings_org_role_mapping.html.markdown
> +# mongodbatlas_cloud_federated_settings_org_role_mapping
```suggestion
# mongodbatlas_federated_settings_org_role_mapping
```

2022-06-28 00:03 UTC, themantissa commented on website/docs/d/federated_settings_org_role_mapping.html.markdown
> +`mongodbatlas_cloud_federated_settings_org_role_mapping` provides an Federated Settings Org Role Mapping datasource. Atlas Cloud Federated Settings Org Role Mapping provides federated settings output
```suggestion
`mongodbatlas_federated_settings_org_role_mapping` provides a federated settings organization role mapping data source. Atlas federated settings organization role mapping provides federated settings outputs for the configured organization role Mapping.
```

2022-06-28 00:03 UTC, themantissa commented on website/docs/d/federated_settings_org_role_mapping.html.markdown
> +resource "mongodbatlas_cloud_federated_settings_org_role_mapping" "org_group_role_mapping_import" {
```suggestion
resource "mongodbatlas_federated_settings_org_role_mapping" "org_group_role_mapping_import" {
```

2022-06-28 00:03 UTC, themantissa commented on website/docs/d/federated_settings_org_role_mapping.html.markdown
> +}
Not updated to match related PR.

2022-06-28 00:03 UTC, themantissa commented on website/docs/d/federated_settings_org_role_mapping.html.markdown
> +data "mongodbatlas_cloud_federated_settings_org_role_mapping" "role_mapping" {
```suggestion
data "mongodbatlas_federated_settings_org_role_mapping" "role_mapping" {
```

2022-06-28 00:03 UTC, themantissa commented on website/docs/d/federated_settings_org_role_mapping.html.markdown
> +* `items_per_page` - (Optional) Number of items to return per page, up to a maximum of 500. Defaults to `100`.
should only be in get all data source?

2022-06-28 00:03 UTC, themantissa commented on website/docs/d/federated_settings_org_role_mapping.html.markdown
> +* `role` - Specifies the Role that is attached to the Role Mapping.
This and another use are pretty different than the source docs: https://www.mongodb.com/docs/atlas/reference/api/role-mapping-return-one/, any particular reason?

2022-06-28 00:03 UTC, themantissa commented on website/docs/d/federated_settings_org_role_mappings.html.markdown
> +layout: "mongodbatlas"
Same as above.

2022-06-28 00:03 UTC, themantissa commented on website/docs/r/federated_settings_identity_provider.html.markdown
> +page_title: "MongoDB Atlas: mongodbatlas_cloud_federated_settings_identity_provider"
```suggestion
page_title: "MongoDB Atlas: mongodbatlas_federated_settings_identity_provider"
```

2022-06-28 00:03 UTC, themantissa commented on website/docs/r/federated_settings_identity_provider.html.markdown
> +sidebar_current: "docs-mongodbatlas-cloud-federated-settings-identity-provider"
```suggestion
sidebar_current: "docs-mongodbatlas-federated-settings-identity-provider"
```

2022-06-28 00:03 UTC, themantissa commented on website/docs/r/federated_settings_identity_provider.html.markdown
> +    Provides an Federated Settings Identity Provider Resource.
```suggestioni
    Provides a federated settings identity provider resource.
```

2022-06-28 00:03 UTC, themantissa commented on website/docs/r/federated_settings_identity_provider.html.markdown
> +# mongodbatlas_cloud_federated_settings_identity_provider
```suggestion
# mongodbatlas_federated_settings_identity_provider
```

2022-06-28 00:03 UTC, themantissa commented on website/docs/r/federated_settings_identity_provider.html.markdown
> +`mongodbatlas_cloud_federated_settings_identity_provider` provides an Atlas Cloud Federated Settings Identity Provider resource provides a subset of settings to be maintained post import of the exist
```suggestion
`mongodbatlas_federated_settings_identity_provider` provides an Atlas federated settings identity provider resource which provides a subset of settings to be managed post import of the existing resource.
```

2022-06-28 00:03 UTC, themantissa commented on website/docs/r/federated_settings_identity_provider.html.markdown
> +## Example Usage
We need a very clear note to users they have to import this first or they will miss it.

```suggestion

~> **IMPORTANT** You **MUST** import this resource before you can manage it with this provider. 

## Example Usage
```

2022-06-28 00:03 UTC, themantissa commented on website/docs/r/federated_settings_identity_provider.html.markdown
> +resource "mongodbatlas_cloud_federated_settings_identity_provider" "identity_provider" {
```suggestion
resource "mongodbatlas_federated_settings_identity_provider" "identity_provider" {
```

2022-06-28 00:03 UTC, themantissa commented on website/docs/r/federated_settings_identity_provider.html.markdown
> +* `issuer_uri` - (Required) Identifier for the issuer of the SAML Assertion.
```suggestion
* `issuer_uri` - (Required) Unique string that identifies the issuer of the SAML Assertion.

2022-06-28 00:03 UTC, themantissa commented on website/docs/r/federated_settings_identity_provider.html.markdown
> +* `sso_url` - (Required) URL of the receiver of the SAML AuthNRequest.
The suggestion is what the source docs has, if you feel yours is more descriptive I'm okay with it too.
```suggestion
* `sso_url` - (Required) Unique string that identifies the intended audience of the SAML assertion.
```

2022-06-28 00:03 UTC, themantissa commented on website/docs/r/federated_settings_identity_provider.html.markdown
> +* `request_binding` - (Required) SAML Authentication Request Protocol binding used to send the AuthNRequest. Atlas supports the following binding values:
Same as above, source is different but if you feel edit better captures I'm okay to change.
```suggestion
* `request_binding` - (Required) SAML Authentication Request Protocol HTTP method binding (POST or REDIRECT) that Federated Authentication uses to send the authentication request. Atlas supports the following binding values:
```

2022-06-28 00:03 UTC, themantissa commented on website/docs/r/federated_settings_identity_provider.html.markdown
> +    - SHA-1
If we just left this SHA-1 the questions would come so fast it would shock you.
```suggestion
* `response_signature_algorithm` - (Required) Signature algorithm that Federated Authentication uses to encrypt the identity provider signature.  Valid values include SHA-1 and SHA-256.
```

2022-06-28 00:03 UTC, themantissa commented on website/docs/r/federated_settings_identity_provider.html.markdown
> +Identity Provider must be imported using federation_settings_id-idp_id, e.g.
```suggestion
Identity Provider **must** be imported before using federation_settings_id-idp_id, e.g.
```

2022-06-28 00:03 UTC, themantissa commented on website/docs/r/federated_settings_org_configs.html.markdown
> +page_title: "MongoDB Atlas: mongodbatlas_cloud_federated_settings_org_config"
```suggestion
page_title: "MongoDB Atlas: mongodbatlas_federated_settings_org_config"
```

2022-06-28 00:03 UTC, themantissa commented on website/docs/r/federated_settings_org_configs.html.markdown
> +    Provides an Federated Settings Organization Configuration.
```suggestion
    Provides a federated settings organization configuration.
```

2022-06-28 00:03 UTC, themantissa commented on website/docs/r/federated_settings_org_configs.html.markdown
> +# mongodbatlas_cloud_federated_settings_org_config
```suggestion
# mongodbatlas_federated_settings_org_config
```

2022-06-28 00:03 UTC, themantissa commented on website/docs/r/federated_settings_org_configs.html.markdown
> +`mongodbatlas_cloud_federated_settings_org_config` provides an Federated Settings Identity Providers datasource. Atlas Cloud Federated Settings Identity Providers provides federated settings outputs
Does not describe this and has _cloud.

2022-06-28 00:03 UTC, themantissa commented on website/docs/r/federated_settings_org_configs.html.markdown
> +resource "mongodbatlas_cloud_federated_settings_org_config" "org_connection" {
```suggestion
resource "mongodbatlas_federated_settings_org_config" "org_connection" {
```

2022-06-28 00:03 UTC, themantissa commented on website/docs/r/federated_settings_org_configs.html.markdown
> +data "mongodbatlas_cloud_federated_settings_org_configs" "org_configs_ds" {
```suggestion
data "mongodbatlas_federated_settings_org_configs" "org_configs_ds" {
```

2022-06-28 00:03 UTC, themantissa commented on website/docs/r/federated_settings_org_configs.html.markdown
> +In addition to all arguments above, the following attributes are exported:
these should be in argument reference

2022-06-28 00:03 UTC, themantissa commented on website/docs/r/federated_settings_org_configs.html.markdown
> +FederatedSettingsOrgConfig must be imported using federation_settings_id-org_id, e.g.
Same as above - need to call out as important at the top of the doc page.

2022-06-28 00:03 UTC, themantissa commented on website/docs/r/federated_settings_org_role_mapping.html.markdown
> +* `org_id` - Unique 24-hexadecimal digit string that identifies the connected organization.
```suggestion
* `org_id` - Unique 24-hexadecimal digit string that identifies the organization that contains your projects.
```

2022-06-28 00:03 UTC, themantissa commented on website/docs/r/federated_settings_org_role_mapping.html.markdown
> +* `group_id` - Unique identifier of the project that owns this Role Mapping Configuration.
```suggestion
* `group_id` - Unique identifier of the project to which you want the role mapping to apply
```

2022-06-28 00:03 UTC, themantissa commented on website/docs/r/federated_settings_org_role_mapping.html.markdown
> +FederatedSettingsOrgRoleMapping must be imported using federation_settings_id-org_id-role_mapping_id, e.g.
Does this have to be imported if there are no role mappings yet?  I think you can setup an IdP without a role mapping (hence this also being a POST).  Also if it does require require it again, should be called out at the top.

2022-06-28 00:03 UTC, themantissa commented on website/mongodbatlas.erb
> +                    <li<%= sidebar_current("docs-mongodbatlas-datasource-federated-settings") %>>
All of these need _cloud removed.

2022-06-28 00:03 UTC, themantissa commented on website/docs/guides/1.4.0-upgrade-guide.html.markdown
> +
Wrote up the entire list - please add:
```suggestion
New Features:

* You can now manage your federated authentication and authorization with  [`mongodbatlas_federated_settings_identity_provider`](https://registry.terraform.io/providers/mongodb/mongodbatlas/latest/docs/resources/federated_settings_identity_provider),   [`mongodbatlas_federated_settings_org_role_mapping`](https://registry.terraform.io/providers/mongodb/mongodbatlas/latest/docs/resources/federated_settings_org_role_mapping), and [`mongodbatlas_federated_settings_org_config`](https://registry.terraform.io/providers/mongodb/mongodbatlas/latest/docs/resources/federated_settings_org_config)
* You can now manage regionalized private endpoint status with [`mongodbatlas_private_endpoint_regional_mode`](https://registry.terraform.io/providers/mongodb/mongodbatlas/latest/docs/resources/private_endpoint_regional_mode)

Changes:

* You can now manage Prometheus with [mongodbatlas_third_party_integration](https://registry.terraform.io/providers/mongodb/mongodbatlas/latest/docs/resources/third_party_integration)
* You can now manage Microsoft Teams with [mongodbatlas_third_party_integration](https://registry.terraform.io/providers/mongodb/mongodbatlas/latest/docs/resources/third_party_integration)
* You can now use the argument `unordered` with [`mongodbatlas_event_trigger`](https://registry.terraform.io/providers/mongodb/mongodbatlas/latest/docs/resources/event_trigger)
* You can now manage project settings with [`mongodbatlas_project`](https://registry.terraform.io/providers/mongodb/mongodbatlas/latest/docs/resources/project)
* You can now enable cloud backup to automatiacially export backups to an AWS bucket with [`mongodbatlas_cloud_backup_schedule `](https://registry.terraform.io/providers/mongodb/mongodbatlas/latest/docs/resources/cloud_backup_schedule)
```

2022-06-28 16:59 UTC, evertsd commented on website/docs/r/federated_settings_org_role_mapping.html.markdown
> +* `org_id` - Unique 24-hexadecimal digit string that identifies the connected organization.
This specific instance was corrected, but is it correct to assume any other instance of `connected organization` should change to `organization that contains your projects`?

2022-06-28 17:00 UTC, evertsd commented on website/docs/guides/1.4.0-upgrade-guide.html.markdown
> +
Thanks a bunch, added

2022-06-29 00:11 UTC, themantissa commented on website/docs/r/federated_settings_org_role_mapping.html.markdown
> +* `org_id` - Unique 24-hexadecimal digit string that identifies the connected organization.
As noted in our standup I only changed the ones where this was different than the source docs at https://www.mongodb.com/docs/atlas/reference/api/federation-configuration/.  Both are technically correct so I'm trusting the docs are slightly different depending on the context (which seems to be the case)

2022-06-29 00:18 UTC, themantissa requested changes
@evertsd fixed a lot, so good progress.  The suggestions that fix using an before Federated to a before Federated still need addressing.  As do the open questions.  If we can get these knocked out 1.4 will be ready!

2022-06-29 00:18 UTC, themantissa commented on website/docs/d/federated_settings_identity_provider.html.markdown
> +    Provides an Federated Settings Organization Identity Provider Datasource.
This one got missed.

2022-06-29 00:18 UTC, themantissa commented on website/docs/d/federated_settings_identity_provider.html.markdown
> +  federation_settings_id     = "627a9687f7f7f7f774de306f14"
@martinstibbe is this like the examples you cited in the https://github.com/mongodb/terraform-provider-mongodbatlas/pull/742?  These are all dummy data?

2022-06-29 00:18 UTC, themantissa commented on website/docs/d/federated_settings_identity_provider.html.markdown
> +* `associated_orgs` - List that contains the configured domains from which users can log in for this IdP.
Missed one

2022-06-29 00:18 UTC, themantissa commented on website/docs/d/federated_settings_org_config.html.markdown
> +    Provides an Federated Settings Organization Configuration.
Missed

2022-06-29 00:18 UTC, themantissa commented on website/docs/d/federated_settings_org_config.html.markdown
> +* `role` - Specifies the Role that is attached to the Role Mapping.
@martinstibbe still an open question

2022-06-29 00:18 UTC, themantissa commented on website/docs/d/federated_settings_org_config.html.markdown
> +### User Conflicts
@martinstibbe still an open question

2022-06-29 00:18 UTC, themantissa commented on website/docs/d/federated_settings_org_role_mapping.html.markdown
> +    Provides an Federated settings Role Mapping Datasource.
Missed

2022-06-29 00:18 UTC, themantissa commented on website/docs/r/federated_settings_identity_provider.html.markdown
> +    Provides an Federated Settings Identity Provider Resource.
Missed

2022-06-29 00:18 UTC, themantissa commented on website/docs/r/federated_settings_identity_provider.html.markdown
> +## Example Usage
Still need to add these.

2022-06-29 00:18 UTC, themantissa commented on website/docs/r/federated_settings_identity_provider.html.markdown
> +Identity Provider must be imported using federation_settings_id-idp_id, e.g.
Still need

2022-06-29 00:18 UTC, themantissa commented on website/docs/r/federated_settings_org_configs.html.markdown
> +    Provides an Federated Settings Organization Configuration.
Missed

2022-06-29 00:18 UTC, themantissa commented on website/docs/r/federated_settings_org_configs.html.markdown
> +FederatedSettingsOrgConfig must be imported using federation_settings_id-org_id, e.g.
Still need

2022-06-29 00:18 UTC, themantissa commented on website/docs/r/federated_settings_org_role_mapping.html.markdown
> +FederatedSettingsOrgRoleMapping must be imported using federation_settings_id-org_id-role_mapping_id, e.g.
Still open - I don't think this one must be.

2022-06-29 17:52 UTC, martinstibbe commented on website/docs/d/federated_settings_identity_provider.html.markdown
> +* `associated_orgs` - List that contains the configured domains from which users can log in for this IdP.
Fixed

2022-06-29 17:53 UTC, martinstibbe commented on website/docs/d/federated_settings_identity_provider.html.markdown
> +* `identity_provider_id` - (Required) Unique 24-hexadecimal digit string that identifies the federated authentication configuration.
Fixed

2022-06-29 17:53 UTC, martinstibbe commented on website/docs/d/federated_settings_identity_provider.html.markdown
> +  federation_settings_id     = "627a9687f7f7f7f774de306f14"
yep 7f7f7f masked

2022-06-29 17:54 UTC, martinstibbe commented on website/docs/d/federated_settings_identity_provider.html.markdown
> +resource "mongodbatlas_cloud_federated_settings_identity_provider" "identity_provider" {
Added variables plus f7f7f7 to break up ids and mangled sso domain / okta urls

2022-06-29 17:54 UTC, martinstibbe commented on website/docs/d/federated_settings_identity_provider.html.markdown
> +`mongodbatlas_cloud_federated_settings_identity_provider` provides an Federated Settings Identity Provider datasource. Atlas Cloud Federated Settings Identity Provider provides federated settings out
Fixed

2022-06-29 17:56 UTC, martinstibbe commented on website/docs/d/federated_settings_identity_provider.html.markdown
> +    Provides an Federated Settings Organization Identity Provider Datasource.
Fixed

2022-06-29 22:04 UTC, martinstibbe commented on website/docs/d/federated_settings_org_config.html.markdown
> +* `identity_provider_id` - Unique 24-hexadecimal digit string that identifies the federated authentication configuration.
Fixed

2022-06-29 22:05 UTC, martinstibbe commented on website/docs/d/federated_settings_org_config.html.markdown
> +* `post_auth_role_grants` - List that contains the default roles granted to users who authenticate through the IdP in a connected organization. If you provide a postAuthRoleGrants field in the reques
Fixed

2022-06-29 22:12 UTC, themantissa commented on website/docs/d/federated_settings_org_config.html.markdown
> +* `domain_allow_list` - List that contains the approved domains from which organization users can log in.
@martinstibbe not fixed.

2022-06-29 22:12 UTC, themantissa commented on website/docs/d/federated_settings_org_config.html.markdown
> +* `domain_restriction_enabled` - Flag that indicates whether domain restriction is enabled for the connected organization.
@martinstibbe not fixed.

2022-06-29 22:12 UTC, themantissa commented on website/docs/d/federated_settings_org_config.html.markdown
> +  ### Role_mappings
@martinstibbe not fixed.

2022-06-29 22:12 UTC, themantissa commented on website/docs/d/federated_settings_org_config.html.markdown
> +* `role` - Specifies the Role that is attached to the Role Mapping.
@martinstibbe not fixed.

2022-06-29 22:12 UTC, themantissa commented on website/docs/d/federated_settings_org_role_mapping.html.markdown
> +}
@martinstibbe not fixed.

2022-06-29 22:12 UTC, themantissa commented on website/docs/d/federated_settings_org_role_mapping.html.markdown
> +* `items_per_page` - (Optional) Number of items to return per page, up to a maximum of 500. Defaults to `100`.
@martinstibbe not fixed.

2022-06-29 22:12 UTC, themantissa commented on website/docs/r/federated_settings_identity_provider.html.markdown
> +## Example Usage
@martinstibbe not fixed.

2022-06-29 22:12 UTC, themantissa commented on website/docs/r/federated_settings_identity_provider.html.markdown
> +* `issuer_uri` - (Required) Identifier for the issuer of the SAML Assertion.
@martinstibbe not fixed.

2022-06-29 22:12 UTC, themantissa commented on website/docs/r/federated_settings_identity_provider.html.markdown
> +* `sso_url` - (Required) URL of the receiver of the SAML AuthNRequest.
@martinstibbe not fixed.

2022-06-29 22:12 UTC, themantissa commented on website/docs/r/federated_settings_identity_provider.html.markdown
> +* `request_binding` - (Required) SAML Authentication Request Protocol binding used to send the AuthNRequest. Atlas supports the following binding values:
@martinstibbe not fixed.

2022-06-29 22:12 UTC, themantissa commented on website/docs/r/federated_settings_identity_provider.html.markdown
> +    - SHA-1
@martinstibbe not fixed.

2022-06-29 22:13 UTC, themantissa commented on website/docs/r/federated_settings_org_configs.html.markdown
> +In addition to all arguments above, the following attributes are exported:
@martinstibbe not fixed.

2022-06-29 22:13 UTC, themantissa commented on website/docs/r/federated_settings_org_configs.html.markdown
> +FederatedSettingsOrgConfig must be imported using federation_settings_id-org_id, e.g.
@martinstibbe not fixed.

2022-06-29 22:16 UTC, martinstibbe commented on website/docs/d/federated_settings_org_config.html.markdown
> +* `domain_allow_list` - List that contains the approved domains from which organization users can log in.
Fixed

2022-06-29 22:18 UTC, martinstibbe commented on website/docs/d/federated_settings_org_config.html.markdown
> +* `domain_restriction_enabled` - Flag that indicates whether domain restriction is enabled for the connected organization.
Fixed

2022-06-29 22:20 UTC, martinstibbe commented on website/docs/d/federated_settings_org_config.html.markdown
> +  ### Role_mappings
Fixed

2022-06-29 22:24 UTC, martinstibbe commented on website/docs/d/federated_settings_org_role_mapping.html.markdown
> +}
Fixed

2022-06-29 22:27 UTC, martinstibbe commented on website/docs/d/federated_settings_org_role_mapping.html.markdown
> +* `items_per_page` - (Optional) Number of items to return per page, up to a maximum of 500. Defaults to `100`.
Removed from singular Datasource

2022-06-29 22:29 UTC, martinstibbe commented on website/docs/r/federated_settings_identity_provider.html.markdown
> +## Example Usage
Added to identity provider resource

2022-06-29 22:29 UTC, martinstibbe commented on website/docs/r/federated_settings_identity_provider.html.markdown
> +* `issuer_uri` - (Required) Identifier for the issuer of the SAML Assertion.
Fixed

2022-06-29 22:30 UTC, martinstibbe commented on website/docs/r/federated_settings_identity_provider.html.markdown
> +* `sso_url` - (Required) URL of the receiver of the SAML AuthNRequest.
Fixed

2022-06-29 22:30 UTC, martinstibbe commented on website/docs/r/federated_settings_identity_provider.html.markdown
> +* `request_binding` - (Required) SAML Authentication Request Protocol binding used to send the AuthNRequest. Atlas supports the following binding values:
Fixed

2022-06-29 22:31 UTC, martinstibbe commented on website/docs/r/federated_settings_identity_provider.html.markdown
> +    - SHA-1
Fixed

2022-06-29 23:24 UTC, martinstibbe commented on website/docs/r/federated_settings_org_configs.html.markdown
> +In addition to all arguments above, the following attributes are exported:
pulled up to arguements

2022-06-29 23:29 UTC, martinstibbe commented on website/docs/r/federated_settings_identity_provider.html.markdown
> +Identity Provider must be imported using federation_settings_id-idp_id, e.g.
Added to identity and org_config

2022-06-30 00:05 UTC, themantissa approved these changes
After many comments we have docs!  Thank you, LGTM!

2022-06-30 00:12 UTC, merged