docs: `*_invite` life cycle clarification
mongodb/terraform-provider-mongodbatlas pull request #756
Opened 2022-06-15 15:09 UTC by morey-tech

## Description

Update the docs to clarify how the lifecycle of the `*_invite` resources works. Indicating that once the invite is accepted the resource is deleted.

Link to any related issue(s):

https://github.com/mongodb/terraform-provider-mongodbatlas/issues/633#issuecomment-993026984

## Type of change:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [x] Documentation fix/enhancement

## Required Checklist:

- [x] I have signed the [MongoDB CLA](https://www.mongodb.com/legal/contributor-agreement)
- [x] I have read the Terraform contribution guidelines
- [x] I have added tests that prove my fix is effective or that my feature works per HashiCorp requirements
- [x] I have added any necessary documentation (if appropriate)
- [x] I have run make fmt and formatted my code

## Further comments

2022-06-16 20:58 UTC, themantissa commented
@morey-tech thank you for the submission. We do have a statement in these docs pages about how invitations work: 

**NOTE**: Possible provider behavior depending on the invitee's action:
>* If the user has not yet accepted the invitation, the provider leaves the invitation as is.
>* If the user has accepted the invitation and is now an organization member, the provider will remove the invitation from the Terraform state.  The invitation must then be removed from the Terraform resource configuration.
>* If the user accepts the invitation and then leaves the organization, the provider will re-add the invitation if the resource definition is not removed from the Terraform configuration.
 
What if we move this up and better clarify some of the points you are making this this PR do you think that will be a bit better?  This obviously is an area that needs better clarification.

2022-06-16 21:36 UTC, morey-tech commented
> @morey-tech thank you for the submission. We do have a statement in these docs pages about how invitations work:
> 
> **NOTE**: Possible provider behavior depending on the invitee's action:
> 
> > * If the user has not yet accepted the invitation, the provider leaves the invitation as is.
> > * If the user has accepted the invitation and is now an organization member, the provider will remove the invitation from the Terraform state.  The invitation must then be removed from the Terraform resource configuration.
> > * If the user accepts the invitation and then leaves the organization, the provider will re-add the invitation if the resource definition is not removed from the Terraform configuration.
> 
> What if we move this up and better clarify some of the points you are making this PR do you think that will be a bit better? This obviously is an area that needs better clarification.

Thanks for pointing that out! I agree that moving it up is important to bring it to the user's attention earlier. This is also typical of resources that may behave differently than a user might assume (i.e., being removed from the state outside without the resource needing to be destroyed). I also think including these notes in the `project_invite` resource docs and not only the `org_invite` would be helpful.

I have updated the PR to integrate the existing note in the `org_invitiation` docs into the changes I am proposing. Please let me know what you think.

2022-06-17 00:10 UTC, themantissa requested changes
Just a small adjustment to make this a bit more clear.

2022-06-17 00:10 UTC, themantissa commented on website/docs/r/project_invitation.html.markdown
> +~> **IMPORTANT:** This resource is specifically to mange the invitations, not the user beyond that. Possible provider behavior depending on the invitee's action:
```suggestion
~> **IMPORTANT:** This resource is only for managing invitations, not for managing the Atlas User being invited. Possible provider behavior depending on the invitee's action:
```

2022-06-17 00:10 UTC, themantissa commented on website/docs/r/org_invitation.html.markdown
> +This resource is specifically to mange the invitations, not the user beyond that. Possible provider behavior depending on the invitee's action:
Just a slight change that should make it even clearer:

```suggestion
~> **IMPORTANT:** This resource is only for managing invitations, not for managing the Atlas User being invited. Possible provider behavior depending on the invitee's action:
```

2022-06-17 20:39 UTC, themantissa approved these changes

2022-06-17 20:40 UTC, themantissa commented
Thanks again @morey-tech !  These changes will go out with our next release.

2022-06-17 20:40 UTC, merged