Maintenance window ds
mongodb/terraform-provider-mongodbatlas pull request #78
Opened 2019-11-26 15:58 UTC by PacoDw

Added: 

- `mongodbatlas_maintenance_window` data source.

- `mongodbatlas_maintenance_window` data source acceptance testing.

- `mongodbatlas_maintenance_window` data source website documentation.

Example configuration:

```hcl
resource "mongodbatlas_maintenance_window" "test" {
  project_id  = "<your-project-id>"
  day_of_week = 3
  hour_of_day = 4
}

data "mongodbatlas_maintenance_window" "test" {
  project_id = "${mongodbatlas_maintenance_window.test.id}"
}
```

2019-12-16 18:36 UTC, themantissa reviewed
Minor edits in doc - only reviewed DS parts of commit, R review in other PR.

2019-12-16 18:36 UTC, themantissa commented on website/docs/d/maintenance_window.html.markdown
> +`mongodbatlas_maintenance_window` provides a Maintenance Window entry datasource. Gets scheduled maintenance event for a project.
slight edit: provides a Maintenance Window entry datasource. Gets information regarding the configured maintenance window for a MongoDB Atlas project.

2019-12-16 18:36 UTC, themantissa commented on website/docs/d/maintenance_window.html.markdown
> +* `hour_of_day` - Hour of the day when you would like the maintenance window to start. This parameter uses the 24-hour clock, where midnight is 0, noon is 12.
Add: Timezone is UTC.

2019-12-16 18:36 UTC, themantissa commented on website/docs/d/maintenance_window.html.markdown
> +* `number_of_deferrals` - Number of times the current maintenance event for this project has been deferred.
Add: Max is two deferrals.

2019-12-18 00:01 UTC, themantissa approved these changes
Approving the data source related work only. Thanks.

2020-01-16 17:42 UTC, marinsalinas requested changes
could you please fix the conflicts otherwise LGTM!

2020-01-17 16:21 UTC, marinsalinas approved these changes
LGTM!

2020-01-17 16:22 UTC, merged