INTMDB-347: [Terraform] cloud_backup is not being correctly imported - issue 768
mongodb/terraform-provider-mongodbatlas pull request #839
Opened 2022-09-12 16:32 UTC by martinstibbe

## Description

[Terraform] cloud_backup is not being correctly imported - issue 768

Link to any related issue(s):
https://github.com/mongodb/terraform-provider-mongodbatlas/issues/768

## Type of change:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Documentation fix/enhancement

## Required Checklist:

- [ ] I have signed the [MongoDB CLA](https://www.mongodb.com/legal/contributor-agreement)
- [ ] I have read the Terraform contribution guidelines
- [ ] I have added tests that prove my fix is effective or that my feature works per HashiCorp requirements
- [ ] I have added any necessary documentation (if appropriate)
- [ ] I have run make fmt and formatted my code

## Further comments

2022-09-12 23:26 UTC, themantissa approved these changes
LGTM!

2022-09-14 09:09 UTC, gssbzn approved these changes
LGTM but some changes some unrelated to the bugfix

2022-09-14 09:10 UTC, blva requested changes

2022-09-14 09:10 UTC, blva commented on mongodbatlas/resource_mongodbatlas_cluster.go
> +		return nil, fmt.Errorf("couldn't import cluster %s in project %s, error: %s", *name, *projectID, err)
do we want to throw the same error as `Clusters.Get`? should probably use different wording here.

2022-09-14 13:22 UTC, martinstibbe commented on mongodbatlas/resource_mongodbatlas_cluster.go
> +		return nil, fmt.Errorf("couldn't import cluster %s in project %s, error: %s", *name, *projectID, err)
Added additional content relating error to backup configuration

2022-09-14 14:42 UTC, blva approved these changes
LGTM

2022-09-14 15:00 UTC, merged