INTMDB-371: PrivateLink Endpoint Timeout
mongodb/terraform-provider-mongodbatlas pull request #841
Opened 2022-09-13 05:32 UTC by evertsd

## Description

Updated default timeout on privatelink_endpoint Create & Delete to match the state change refresh timeout for these actions.
- This bumps the timeout from 20m to 60m
- It allows configuration of the tf timeout to more than 60m
- However the state change refresh timeout *does not honor* said configuration, so for the time being 60m is the max wait time to create & delete privatelink_endpoint resources.
- Am open to feedback on what the default & max timeouts should be for these operations.

Link to any related issue(s):
Closes #806

## Type of change:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Documentation fix/enhancement

## Required Checklist:

- [ ] I have signed the [MongoDB CLA](https://www.mongodb.com/legal/contributor-agreement)
- [ ] I have read the Terraform contribution guidelines
- [ ] I have added tests that prove my fix is effective or that my feature works per HashiCorp requirements
- [ ] I have added any necessary documentation (if appropriate)
- [ ] I have run make fmt and formatted my code

## Further comments

2022-09-13 20:45 UTC, themantissa requested changes
If create, delete and refresh will now honor: 
timeouts {
    create = "60m"
  }
Then I think we should make a note of this in the private link docs.  Agree?

2022-09-13 21:56 UTC, evertsd commented
I've added documentation to the resource, including an example on usage, let me know if / how I can improve.

Do you believe our docs should link to the terraform docs on this feature?
https://www.terraform.io/plugin/sdkv2/resources/retries-and-customizable-timeouts

2022-09-14 01:53 UTC, themantissa requested changes
@evertsd I like the suggestion to link to the docs.  Something like learn more about timeouts here.  With the link on here.  TY!

2022-09-14 14:10 UTC, evertsd commented
Done! Thanks for the specific suggestion on copy

2022-09-14 14:43 UTC, themantissa approved these changes
LGTM!

2022-09-14 16:33 UTC, gssbzn approved these changes
LGTM

2022-09-15 15:17 UTC, merged