Add APIx1 CODEOWNER
mongodb/terraform-provider-mongodbatlas pull request #894
Opened 2022-10-31 15:37 UTC by Zuhairahmed

This tag pulls current APIx1 on-call onto PR review

## Description

Please include a summary of the fix/feature/change, including any relevant motivation and context.

Link to any related issue(s):

## Type of change:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Documentation fix/enhancement

## Required Checklist:

- [ ] I have signed the [MongoDB CLA](https://www.mongodb.com/legal/contributor-agreement)
- [ ] I have read the Terraform contribution guidelines
- [ ] I have added tests that prove my fix is effective or that my feature works per HashiCorp requirements
- [ ] I have added any necessary documentation (if appropriate)
- [ ] I have run make fmt and formatted my code

## Further comments

2022-10-31 15:41 UTC, themantissa requested changes
See my comment regarding errors

2022-10-31 15:41 UTC, themantissa commented on .github/CODEOWNERS
> +
There are errors being reported by github on the entries below this line.   I'd just delete them as /examples should be the two above and the other is superseded by APIx1

2022-10-31 16:17 UTC, Zuhairahmed commented on .github/CODEOWNERS
> +
makes sense, deleted.

2022-10-31 16:30 UTC, martinstibbe approved these changes
LGTM

2022-10-31 19:22 UTC, themantissa approved these changes
Looks good, ty!

2022-11-01 08:40 UTC, andreaangiolillo approved these changes
LGTM

2022-11-01 14:10 UTC, merged