Feat: Global Cluster Configuration Resource and Data Source.
mongodb/terraform-provider-mongodbatlas pull request #90
Opened 2019-12-12 00:29 UTC by marinsalinas

Added:

* `mongodbatlas_global_cluster_config` resource.
* `mongodbatlas_global_cluster_config` resource acceptance tests.
* `mongodbatlas_global_cluster_config` website documentation.
* `mongodbatlas_global_cluster_config` data source.
* `mongodbatlas_global_cluster_config` data source acceptance tests.
* `mongodbatlas_global_cluster_config` data source website documentation.
 

## Example Usage

```hcl
	resource "mongodbatlas_cluster" "test" {
		project_id              = "<YOUR-PROJECT-ID>"
		name                    = "<CLUSTER-NAME>"
		disk_size_gb            = 80
		num_shards              = 1
		backup_enabled          = false
		provider_backup_enabled = true
		cluster_type            = "GEOSHARDED"
		
		//Provider Settings "block"
		provider_name               = "AWS"
		provider_disk_iops          = 240
		provider_instance_size_name = "M30"
		
		replication_specs {
			zone_name  = "Zone 1"
			num_shards = 2
			regions_config {
			region_name     = "EU_CENTRAL_1"
			electable_nodes = 3
			priority        = 7
			read_only_nodes = 0
			}
		}
		
		replication_specs { 
			zone_name  = "Zone 2"
			num_shards = 2
			regions_config {
			region_name     = "US_EAST_2"
			electable_nodes = 3
			priority        = 7
			read_only_nodes = 0
			}
		}
	}
	
	resource "mongodbatlas_global_cluster_config" "config" {
		project_id = mongodbatlas_cluster.test.project_id
		cluster_name = mongodbatlas_cluster.test.name
	
		managed_namespaces {
			db 				 = "mydata"
			collection 		 = "publishers"
			custom_shard_key = "city"
		}
	
		custom_zone_mappings {
			location ="CA"
			zone =  "Zone 1"
		}
	}

    data "mongodbatlas_global_cluster_config" "config" {
		project_id = mongodbatlas_global_cluster_config.config.project_id
		cluster_name = mongodbatlas_global_cluster_config.config.cluster_name
	}
```

2019-12-12 16:40 UTC, PacoDw approved these changes
LGTM! 😄 👍

2020-01-31 04:01 UTC, themantissa requested changes
Just a few small items but overall LGTM!

2020-01-31 04:01 UTC, themantissa commented on mongodbatlas/data_source_mongodbatlas_global_cluster_config_test.go
> +		num_shards              = 1
This shouldn't work with num_shards 1 - as the docs for num_shards states "Do not include in the request body for Global Clusters."

2020-01-31 04:01 UTC, themantissa commented on mongodbatlas/data_source_mongodbatlas_global_cluster_config_test.go
> +		backup_enabled          = %s
Recent change but so you know - backup_enabled must be false or not used for new AWS clusters now. Only Cloud Provider Snapshots are supported for AWS now.

2020-01-31 04:01 UTC, themantissa commented on website/docs/d/global_cluster_config.html.markdown
> +		num_shards              = 1
Don't think this will work with num_shards here, working example does not have.

2020-01-31 04:01 UTC, themantissa commented on website/docs/d/global_cluster_config.html.markdown
> +		backup_enabled          = false
probably good to just remove backup_enabled from AWS from here on out since provider_backup_enabled is now the desired backup for new AWS clusters.

2020-01-31 04:01 UTC, themantissa commented on website/docs/r/global_cluster_config.html.markdown
> +		backup_enabled          = false
This one looks right so think others just need updating to match!

2020-01-31 04:01 UTC, themantissa commented on website/docs/r/global_cluster_config.html.markdown
> +### Example AWS cluster
Don't think we need this one here.

2020-01-31 04:01 UTC, themantissa commented on website/docs/r/global_cluster_config.html.markdown
> +
Add a header?  Like 
 ### Example Global cluster config

2020-02-03 17:41 UTC, themantissa approved these changes
LGTM!  Thanks!

2020-02-03 22:27 UTC, merged