INTMDB-438 ForceNew on cluster name change
mongodb/terraform-provider-mongodbatlas pull request #902
Opened 2022-11-07 16:06 UTC by evertsd

## Description

Cluster name changed could result in corrupted state file. The proper behavior is to force a new cluster on name change

Link to any related issue(s):

## Type of change:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Documentation fix/enhancement

## Required Checklist:

- [ ] I have signed the [MongoDB CLA](https://www.mongodb.com/legal/contributor-agreement)
- [ ] I have read the Terraform contribution guidelines
- [ ] I have added tests that prove my fix is effective or that my feature works per HashiCorp requirements
- [ ] I have added any necessary documentation (if appropriate)
- [ ] I have run make fmt and formatted my code

## Further comments

2022-11-07 16:39 UTC, andreaangiolillo approved these changes
LGTM

2022-11-10 00:02 UTC, themantissa approved these changes
Didn't want to do this till we had termination protection but now that we do, we can do this right. TY!

2022-11-10 00:55 UTC, Zuhairahmed requested changes
Can we move this v1.6.1 release branch?

2022-11-10 15:56 UTC, evertsd commented
Ok @Zuhairahmed this is now going into `release-staging-v1.6.1`

2022-11-10 16:30 UTC, Zuhairahmed approved these changes
Thanks @evertsd! LGTM

2022-11-10 16:40 UTC, merged