INTMDB-434 - Fixed private_endpoint output documentation
mongodb/terraform-provider-mongodbatlas pull request #907
Opened 2022-11-08 21:52 UTC by evertsd

## Description

Updated documentation on cluster connection_strings to contain instructions on how to output a private_endpoint srv_connection_string given an endpoint_id

Closes #713 

## Type of change:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Documentation fix/enhancement

## Required Checklist:

- [ ] I have signed the [MongoDB CLA](https://www.mongodb.com/legal/contributor-agreement)
- [ ] I have read the Terraform contribution guidelines
- [ ] I have added tests that prove my fix is effective or that my feature works per HashiCorp requirements
- [ ] I have added any necessary documentation (if appropriate)
- [ ] I have run make fmt and formatted my code

## Further comments

2022-11-10 00:06 UTC, themantissa requested changes
Since we have GCP PSC as well now should we add that example too?

2022-11-10 00:55 UTC, Zuhairahmed requested changes
Can we move this to v1.6.1 release branch?

2022-11-19 15:51 UTC, evertsd commented
@themantissa I changed the format a bit to be a generic example for getting a connection_string from a endpoint_service_id. 

The specific example given is for GCP, however it would work for Azure, AWS, or whatever other theoretical provider depending on how the endpoint_service_id is set. 

Then I've linked to full examples for AWS, Azure, and GCP.

2022-11-24 11:09 UTC, matt-condon approved these changes

2022-11-29 17:01 UTC, Zuhairahmed requested changes
Few minor edits and added a few formatting/typo commits directly. Also can you update Advanced Cluster docs as you did with Cluster to add the entire Return Connection String examples to help users? 

[Example - Return a Connection String](https://registry.terraform.io/providers/mongodb/mongodbatlas/latest/docs/resources/cluster#example---return-a-connection-string)

2022-11-29 17:01 UTC, Zuhairahmed commented on examples/azure-atlas-privatelink/Readme.md
> +* A MongoDB Atlas account
```suggestion
* MongoDB Atlas account
```

2022-11-29 17:01 UTC, Zuhairahmed commented on examples/gcp-atlas-privatelink/Readme.md
> +* A MongoDB Atlas account
```suggestion
* MongoDB Atlas account
```

2022-11-29 17:01 UTC, Zuhairahmed commented on examples/gcp-atlas-privatelink/Readme.md
> +* Google account
```suggestion
* Google Cloud account
```

2022-11-29 17:35 UTC, evertsd commented
Thanks for the feedback and suggestions @Zuhairahmed -- I've implemented and applied them.

2022-11-29 21:30 UTC, Zuhairahmed approved these changes
LGTM! Thanks @evertsd feel free to merge

2022-11-29 22:03 UTC, merged